'use strict';

module.exports = {
  category: "Animals & Nature",
  questions: [
    // Level 1 — Easy
    [1, "What is the fastest land animal?", "Cheetah", "Lion", "Horse", "Gazelle"],
    [1, "Which animal is known as the 'King of the Jungle'?", "Lion", "Tiger", "Elephant", "Gorilla"],
    [1, "How many legs does an insect have?", "6", "8", "4", "10"],
    [1, "What do pandas mainly eat?", "Bamboo", "Fish", "Fruit", "Insects"],
    [1, "Which bird is a symbol of peace?", "Dove", "Eagle", "Crow", "Parrot"],
    [1, "What is a baby dog called?", "Puppy", "Kitten", "Foal", "Calf"],
    [1, "Which animal has a long trunk?", "Elephant", "Rhino", "Hippo", "Giraffe"],
    [1, "Where do polar bears live?", "The Arctic", "Antarctica", "The Sahara", "The Amazon"],
    [1, "What do caterpillars eat most?", "Leaves", "Meat", "Seeds", "Fish"],
    [1, "Which animal is famous for changing its color?", "Chameleon", "Frog", "Snake", "Turtle"],
    [1, "Which is the largest bird in the world?", "Ostrich", "Eagle", "Albatross", "Emu"],
    [1, "What does a cow drink to make milk?", "Water", "Milk", "Juice", "Oil"],
    [1, "Which animal is known for its black and white stripes?", "Zebra", "Tiger", "Skunk", "Panda"],
    [1, "Which sea creature has eight arms?", "Octopus", "Squid", "Starfish", "Jellyfish"],
    [1, "What is a group of fish called?", "School", "Herd", "Pack", "Flock"],
    [1, "Which animal hops and carries its baby in a pouch?", "Kangaroo", "Rabbit", "Frog", "Squirrel"],
    [1, "What do bees collect from flowers?", "Nectar", "Water", "Seeds", "Leaves"],
    [1, "Which animal sleeps upside down?", "Bat", "Owl", "Sloth", "Monkey"],
    [1, "What color are most leaves in summer?", "Green", "Red", "Blue", "Purple"],
    [1, "Which pet is known for purring?", "Cat", "Dog", "Hamster", "Fish"],

    // Level 2 — Medium
    [2, "What is the largest species of shark?", "Whale shark", "Great white shark", "Hammerhead", "Tiger shark"],
    [2, "Which animal is the largest living land animal?", "African elephant", "Hippopotamus", "White rhinoceros", "Giraffe"],
    [2, "What is a baby frog called?", "Tadpole", "Calf", "Kit", "Cub"],
    [2, "Which bird can fly backward?", "Hummingbird", "Sparrow", "Eagle", "Pigeon"],
    [2, "What is a male honeybee called?", "Drone", "Worker", "Queen", "Soldier"],
    [2, "Which animal has the longest lifespan among these?", "Galápagos tortoise", "Elephant", "Parrot", "Horse"],
    [2, "What is the only continent without native snakes or reptiles on land?", "Antarctica", "Australia", "Europe", "South America"],
    [2, "Which mammal lays eggs?", "Platypus", "Kangaroo", "Koala", "Beaver"],
    [2, "What is a female deer called?", "Doe", "Mare", "Ewe", "Sow"],
    [2, "Which tree produces acorns?", "Oak", "Maple", "Pine", "Birch"],
    [2, "What do you call animals that eat both plants and meat?", "Omnivores", "Herbivores", "Carnivores", "Detritivores"],
    [2, "Which big cat has a spotted coat with rosettes and lives in Africa and Asia?", "Leopard", "Cheetah", "Jaguar", "Lynx"],
    [2, "Which animal is known for building dams?", "Beaver", "Otter", "Muskrat", "Badger"],
    [2, "What is the largest type of penguin?", "Emperor penguin", "King penguin", "Adélie penguin", "Gentoo penguin"],
    [2, "Which insect is known for its glowing abdomen?", "Firefly", "Ladybug", "Dragonfly", "Moth"],
    [2, "What is the tallest type of grass?", "Bamboo", "Sugarcane", "Corn", "Wheat"],
    [2, "What is a group of wolves called?", "Pack", "Pride", "Herd", "Murder"],
    [2, "Which ocean animal is the largest animal ever known to have lived?", "Blue whale", "Megalodon", "Whale shark", "Argentinosaurus"],
    [2, "Which bird is known for mimicking human speech?", "Parrot", "Owl", "Penguin", "Flamingo"],
    [2, "What gives flamingos their pink color?", "Their diet (carotenoids)", "Sunburn", "Genetics only", "Mud baths"],

    // Level 3 — Hard
    [3, "What is the largest living species of lizard?", "Komodo dragon", "Green iguana", "Monitor lizard (Nile)", "Gila monster"],
    [3, "How many stomach compartments does a cow have?", "4", "1", "2", "6"],
    [3, "Which animal has the strongest bite force among living animals?", "Saltwater crocodile", "Great white shark", "Hippopotamus", "Lion"],
    [3, "What is the tallest tree species in the world?", "Coast redwood", "Giant sequoia", "Douglas fir", "Mountain ash"],
    [3, "Which bird has the largest wingspan?", "Wandering albatross", "Andean condor", "Bald eagle", "Pelican"],
    [3, "What is a group of owls called?", "Parliament", "Murder", "Gaggle", "Colony"],
    [3, "Which animal's fingerprints are almost indistinguishable from humans'?", "Koala", "Chimpanzee", "Gorilla", "Orangutan"],
    [3, "What is the fastest bird in a dive?", "Peregrine falcon", "Golden eagle", "Swift", "Hawk"],
    [3, "What type of animal is a Portuguese man o' war?", "Siphonophore (a colony of organisms)", "Jellyfish (single animal)", "Squid", "Fish"],
    [3, "Which plant is known for trapping and digesting insects with snapping leaves?", "Venus flytrap", "Pitcher plant", "Sundew", "Bladderwort"],
    [3, "Which flightless Australian bird is the second-tallest bird in the world?", "Emu", "Cassowary", "Kiwi", "Rhea"],
    [3, "How many teeth does an adult human usually have?", "32", "28", "30", "36"],
    [3, "Which animal is the closest living relative of humans?", "Chimpanzee and bonobo", "Gorilla", "Orangutan", "Gibbon"],
    [3, "Which animal is known to sleep standing up and lie down only briefly?", "Horse", "Dog", "Pig", "Lion"],
    [3, "What is the largest rainforest in the world?", "Amazon", "Congo", "Daintree", "Borneo"],
    [3, "Which gas do plants release during photosynthesis?", "Oxygen", "Carbon dioxide", "Nitrogen", "Methane"],
    [3, "How long is an elephant's pregnancy, roughly?", "22 months", "9 months", "12 months", "36 months"],
    [3, "Which fish is famous for swimming upstream to spawn?", "Salmon", "Tuna", "Cod", "Trout"],
    [3, "What is a baby swan called?", "Cygnet", "Gosling", "Duckling", "Eaglet"],
    [3, "Which two animals appear on Australia's coat of arms?", "Kangaroo and emu", "Koala and kangaroo", "Emu and platypus", "Kookaburra and koala"],

    // Level 4 — Expert
    [4, "What is the scientific name for humans?", "Homo sapiens", "Homo erectus", "Homo habilis", "Pan troglodytes"],
    [4, "Which animal has the largest eyes in the animal kingdom?", "Colossal squid", "Blue whale", "Ostrich", "Giant octopus"],
    [4, "Which is the only big cat that cannot fully retract its claws?", "Cheetah", "Leopard", "Snow leopard", "Jaguar"],
    [4, "What is the scientific name of the Great Basin bristlecone pine, home to some of Earth's oldest trees?", "Pinus longaeva", "Sequoia sempervirens", "Quercus robur", "Taxus baccata"],
    [4, "What color is a polar bear's skin under its fur?", "Black", "White", "Pink", "Grey"],
    [4, "Which mammal has the most powerful sense of smell, with up to 300 million scent receptors?", "Dog (bloodhound)", "Cat", "Shark", "Horse"],
    [4, "What is the term for animals that are active at dawn and dusk?", "Crepuscular", "Nocturnal", "Diurnal", "Matutinal"],
    [4, "How many species of bears are there in the world?", "8", "5", "6", "12"],
    [4, "What is the world's largest flower, smelling of rotting meat?", "Rafflesia arnoldii", "Titan arum", "Corpse lily of Peru", "Giant water lily"],
    [4, "Which animal is famously able to regenerate its heart and spinal cord?", "Axolotl", "Starfish", "Gecko", "Planarian"],
    [4, "What is the collective noun for a group of flamingos?", "Flamboyance", "Parade", "Blush", "Ballet"],
    [4, "Which bird lays the largest eggs relative to its body size?", "Kiwi", "Ostrich", "Emu", "Hummingbird"],
    [4, "What is the fastest fish in the ocean (commonly cited)?", "Sailfish", "Bluefin tuna", "Mako shark", "Swordfish"],
    [4, "Which animal produces the loudest sound of any animal?", "Sperm whale", "Blue whale", "Howler monkey", "Lion"],
    [4, "What is the process by which a caterpillar becomes a butterfly called?", "Metamorphosis", "Mitosis", "Photosynthesis", "Molting"],
    [4, "Which snake is the longest in the world?", "Reticulated python", "Green anaconda", "King cobra", "Burmese python"],
    [4, "Tardigrades are also known by what nickname?", "Water bears", "Moss pigs", "Sea mice", "Rock fleas"],
    [4, "Which tree's leaves are the only food of koalas?", "Eucalyptus", "Acacia", "Bamboo", "Banksia"],
    [4, "What is the largest species of deer?", "Moose", "Elk", "Caribou", "Red deer"],
    [4, "What is a swirling flock of starlings called?", "Murmuration", "Murder", "Parliament", "Flamboyance"],
  ],
};
