'use strict';

module.exports = {
  category: "Food & Drink",
  questions: [
    // Level 1 — Easy
    [1, "What is the main ingredient in guacamole?", "Avocado", "Tomato", "Lime", "Pepper"],
    [1, "Which fruit is known for keeping the doctor away?", "Apple", "Banana", "Orange", "Grape"],
    [1, "What do you call a sandwich with bacon, lettuce and tomato?", "BLT", "Club", "Reuben", "Cuban"],
    [1, "Which country is pizza originally from?", "Italy", "United States", "Greece", "France"],
    [1, "What is sushi traditionally wrapped in?", "Seaweed", "Rice paper", "Lettuce", "Tortilla"],
    [1, "Which food is made by bees?", "Honey", "Jam", "Syrup", "Butter"],
    [1, "What is the main ingredient in french fries?", "Potatoes", "Carrots", "Corn", "Rice"],
    [1, "Which nut is used to make peanut butter?", "Peanut", "Almond", "Cashew", "Walnut"],
    [1, "Which drink is made from roasted beans and contains caffeine?", "Coffee", "Lemonade", "Milk", "Juice"],
    [1, "What color is the inside of a watermelon?", "Red or pink", "Green", "Orange", "White"],
    [1, "Which dairy product is made by churning cream?", "Butter", "Cheese", "Yogurt", "Milk"],
    [1, "What kind of food is cheddar?", "Cheese", "Bread", "Sausage", "Fish"],
    [1, "Which fruit is dried to make raisins?", "Grapes", "Plums", "Cherries", "Figs"],
    [1, "Popcorn is made from which grain?", "Corn", "Wheat", "Rice", "Oats"],
    [1, "Which vegetable is famous for making you cry when you cut it?", "Onion", "Carrot", "Potato", "Cucumber"],
    [1, "Tacos come from the cuisine of which country?", "Mexico", "Spain", "Brazil", "Peru"],
    [1, "Which meal is usually eaten in the morning?", "Breakfast", "Dinner", "Supper", "Lunch"],
    [1, "What is the main ingredient of an omelette?", "Eggs", "Flour", "Milk", "Cheese"],
    [1, "Which fruit is yellow, curved and peeled before eating?", "Banana", "Lemon", "Mango", "Pear"],
    [1, "Which sweet treat is frozen and often served in a cone?", "Ice cream", "Cake", "Pie", "Cookie"],

    // Level 2 — Medium
    [2, "What is the main ingredient in hummus?", "Chickpeas", "Lentils", "Black beans", "Peas"],
    [2, "Which country is the croissant most associated with?", "France", "Italy", "Belgium", "Switzerland"],
    [2, "What type of pasta is shaped like little ears?", "Orecchiette", "Penne", "Farfalle", "Fusilli"],
    [2, "Which spice gives curry its yellow color?", "Turmeric", "Paprika", "Saffron", "Cumin"],
    [2, "What is tofu made from?", "Soybeans", "Rice", "Chickpeas", "Wheat"],
    [2, "Which country is famous for kimchi?", "South Korea", "Japan", "China", "Vietnam"],
    [2, "What is the Japanese dish of raw sliced fish (without rice) called?", "Sashimi", "Tempura", "Ramen", "Udon"],
    [2, "Which cheese is traditionally used on a Margherita pizza?", "Mozzarella", "Cheddar", "Parmesan", "Gouda"],
    [2, "What is the main ingredient in a traditional falafel?", "Chickpeas or fava beans", "Potato", "Lentils", "Rice"],
    [2, "Which fruit has its seeds on the outside?", "Strawberry", "Raspberry", "Blueberry", "Kiwi"],
    [2, "What is the national dish of Spain, made with rice and saffron?", "Paella", "Risotto", "Jambalaya", "Biryani"],
    [2, "Which drink is traditionally served in a 'teapot'?", "Tea", "Coffee", "Hot chocolate", "Soup"],
    [2, "Which nut is used to make marzipan?", "Almond", "Hazelnut", "Pistachio", "Walnut"],
    [2, "Which Italian dessert means 'pick me up'?", "Tiramisu", "Panna cotta", "Cannoli", "Gelato"],
    [2, "What is the main ingredient in a traditional pesto?", "Basil", "Parsley", "Spinach", "Mint"],
    [2, "Which country do nachos originally come from?", "Mexico", "United States", "Spain", "Argentina"],
    [2, "What is a 'quesadilla' filled mostly with?", "Cheese", "Rice", "Fruit", "Fish"],
    [2, "Which grain is used to make traditional risotto?", "Arborio rice", "Basmati rice", "Barley", "Quinoa"],
    [2, "What fruit is the main ingredient in a piña colada (with coconut)?", "Pineapple", "Mango", "Banana", "Papaya"],
    [2, "Which type of bread is a long, thin French loaf?", "Baguette", "Ciabatta", "Brioche", "Focaccia"],

    // Level 3 — Hard
    [3, "Which spice is the most expensive by weight?", "Saffron", "Vanilla", "Cardamom", "Cinnamon"],
    [3, "What is the main ingredient in the Middle Eastern dish baba ghanoush?", "Eggplant", "Chickpeas", "Zucchini", "Tomato"],
    [3, "Which country does the dish 'pho' come from?", "Vietnam", "Thailand", "Cambodia", "Laos"],
    [3, "What is the Scottish dish made from sheep's heart, liver and lungs?", "Haggis", "Black pudding", "Scotch egg", "Shepherd's pie"],
    [3, "Which cheese is famous for its holes and comes from Switzerland?", "Emmental", "Brie", "Gouda", "Feta"],
    [3, "What is the name of the Japanese rice wine?", "Sake", "Soju", "Mirin", "Baijiu"],
    [3, "Which fruit is known as the 'king of fruits' in Southeast Asia and has a strong smell?", "Durian", "Jackfruit", "Mangosteen", "Rambutan"],
    [3, "What is the main ingredient in traditional Japanese miso?", "Fermented soybeans", "Seaweed", "Rice flour", "Fish"],
    [3, "What does 'al dente' mean when cooking pasta?", "Firm to the bite", "Very soft", "Overcooked", "Served cold"],
    [3, "Which country is the largest producer of coffee in the world?", "Brazil", "Colombia", "Vietnam", "Ethiopia"],
    [3, "Which Greek cheese is often used in salads and made from sheep's milk?", "Feta", "Halloumi", "Ricotta", "Manchego"],
    [3, "What is 'ghee'?", "Clarified butter", "Spiced yogurt", "Fried bread", "Lentil soup"],
    [3, "Which pepper is used to make Tabasco sauce?", "Tabasco pepper", "Jalapeño", "Habanero", "Cayenne"],
    [3, "What is the main ingredient in a traditional Spanish gazpacho?", "Tomato", "Cucumber", "Potato", "Pumpkin"],
    [3, "Which type of pastry is used for éclairs and profiteroles?", "Choux pastry", "Puff pastry", "Shortcrust", "Filo"],
    [3, "What Korean dish of mixed rice is served in a hot stone bowl?", "Dolsot bibimbap", "Bulgogi", "Japchae", "Tteokbokki"],
    [3, "Which meat is used in a traditional Reuben sandwich?", "Corned beef", "Turkey", "Ham", "Roast chicken"],
    [3, "Matcha is a powdered form of which drink?", "Green tea", "Black tea", "Coffee", "Hot chocolate"],
    [3, "Which bean is used to make chocolate?", "Cacao", "Coffee", "Vanilla", "Carob"],
    [3, "What is 'mochi' made from?", "Glutinous rice", "Wheat flour", "Cornstarch", "Potato starch"],

    // Level 4 — Expert
    [4, "What is the Scoville scale used to measure?", "Spiciness of peppers", "Sweetness of fruit", "Acidity of wine", "Saltiness of food"],
    [4, "Which pepper once held the Guinness record as the world's hottest (2013–2023)?", "Carolina Reaper", "Ghost pepper", "Trinidad Scorpion", "Habanero"],
    [4, "What is the French term for a mixture of diced onions, carrots and celery?", "Mirepoix", "Roux", "Bouquet garni", "Julienne"],
    [4, "Which mushroom is one of the most expensive foods in the world, found underground?", "Truffle", "Morel", "Porcini", "Shiitake"],
    [4, "What is the main ingredient in the Hawaiian dish 'poi'?", "Taro root", "Pineapple", "Coconut", "Breadfruit"],
    [4, "What is the name of the Italian cured ham, often sliced thin?", "Prosciutto", "Mortadella", "Pancetta", "Salami"],
    [4, "What gas makes bread dough rise?", "Carbon dioxide", "Oxygen", "Nitrogen", "Hydrogen"],
    [4, "Which country is the origin of the dish 'ceviche' (as commonly claimed)?", "Peru", "Mexico", "Chile", "Ecuador"],
    [4, "What is the name of the fermented tea drink with a 'SCOBY'?", "Kombucha", "Kefir", "Kvass", "Chai"],
    [4, "What is 'umami' commonly described as?", "A savory taste", "A sour taste", "A bitter taste", "A sweet taste"],
    [4, "Which French sauce is made from egg yolks, butter and lemon juice?", "Hollandaise", "Béchamel", "Velouté", "Espagnole"],
    [4, "Which plant do vanilla beans come from?", "An orchid", "A palm tree", "A lily", "A vine of the bean family"],
    [4, "What is 'wasabi' traditionally made from?", "A root related to horseradish", "Green chili", "Seaweed", "Mustard seeds only"],
    [4, "Which Japanese fish dish can be deadly if prepared incorrectly?", "Fugu (pufferfish)", "Unagi (eel)", "Saba (mackerel)", "Maguro (tuna)"],
    [4, "What is the name of the Indian bread baked in a tandoor oven?", "Naan", "Chapati", "Puri", "Paratha"],
    [4, "What does a sommelier specialize in?", "Wine", "Cheese", "Bread", "Chocolate"],
    [4, "Which nut is technically a seed from a drupe and grows on a tree in the cashew family?", "Pistachio", "Peanut", "Hazelnut", "Pecan"],
    [4, "What is the national dish of Hungary, a stew seasoned with paprika?", "Goulash", "Borscht", "Pierogi", "Schnitzel"],
    [4, "Which country produces Gruyère cheese?", "Switzerland", "France", "Italy", "Netherlands"],
    [4, "What is the key ingredient in the Japanese dish 'tamagoyaki'?", "Egg", "Tofu", "Fish cake", "Seaweed"],
  ],
};
