'use strict';

module.exports = {
  category: "Gaming",
  questions: [
    // Level 1 — Easy
    [1, "What is the name of the princess Mario usually rescues?", "Peach", "Daisy", "Zelda", "Rosalina"],
    [1, "What company makes the PlayStation?", "Sony", "Microsoft", "Nintendo", "Sega"],
    [1, "Which game features a battle bus?", "Fortnite", "PUBG", "Apex Legends", "Warzone"],
    [1, "What color is Sonic the Hedgehog?", "Blue", "Red", "Green", "Yellow"],
    [1, "In Among Us, what is the name for the hidden killer?", "Impostor", "Traitor", "Saboteur", "Mole"],
    [1, "Which company makes the Xbox?", "Microsoft", "Sony", "Nintendo", "Valve"],
    [1, "What is Mario's brother's name?", "Luigi", "Wario", "Toad", "Yoshi"],
    [1, "In Minecraft, what green creature explodes near players?", "Creeper", "Zombie", "Enderman", "Slime"],
    [1, "Which yellow character eats dots and avoids ghosts?", "Pac-Man", "Kirby", "Pikachu", "Bomberman"],
    [1, "Which Pokémon is Ash Ketchum's famous partner?", "Pikachu", "Charmander", "Bulbasaur", "Squirtle"],
    [1, "What falling-block puzzle game is famous for its 'L' and 'T' shapes?", "Tetris", "Candy Crush", "Bejeweled", "Dr. Mario"],
    [1, "Which company makes the Switch console?", "Nintendo", "Sony", "Microsoft", "Sega"],
    [1, "What is the name of the pink puffball hero from Dream Land?", "Kirby", "Jigglypuff", "Yoshi", "Toad"],
    [1, "Which game has players build with blocks in a world made of cubes?", "Minecraft", "Roblox", "Terraria", "Fortnite"],
    [1, "What is the green dinosaur that Mario rides?", "Yoshi", "Bowser", "Birdo", "Koopa"],
    [1, "In Angry Birds, what do the birds attack?", "Pigs", "Cats", "Worms", "Frogs"],
    [1, "Which platform lets players create and play user-made games, using Robux?", "Roblox", "Steam", "Minecraft", "itch.io"],
    [1, "What is the name of Mario's big turtle-like enemy?", "Bowser", "Ganon", "Ridley", "King Dedede"],
    [1, "Which game series features the hero Master Chief?", "Halo", "Destiny", "Gears of War", "Call of Duty"],
    [1, "In Pokémon, what item is used to catch Pokémon?", "Poké Ball", "Master Key", "Pokécube", "Capture Net"],

    // Level 2 — Medium
    [2, "In Minecraft, what material do you need to make a Nether portal?", "Obsidian", "Bedrock", "Netherrack", "Cobblestone"],
    [2, "Which Pokémon is #25 in the National Pokédex?", "Pikachu", "Eevee", "Jigglypuff", "Charmander"],
    [2, "Link is the hero of which game series?", "The Legend of Zelda", "Final Fantasy", "Kingdom Hearts", "Metroid"],
    [2, "Tetris was originally created in which country?", "Soviet Union", "Japan", "USA", "Finland"],
    [2, "What is the best-selling video game of all time (as of 2024)?", "Minecraft", "GTA V", "Tetris (EA)", "Wii Sports"],
    [2, "In which city is Grand Theft Auto V mainly set?", "Los Santos", "Liberty City", "Vice City", "San Fierro"],
    [2, "Which company developed 'Fortnite'?", "Epic Games", "Activision", "Valve", "Riot Games"],
    [2, "Which game features the characters Steve and Alex?", "Minecraft", "Terraria", "Roblox", "Stardew Valley"],
    [2, "What is the name of the main character in the 'God of War' series?", "Kratos", "Atreus", "Ares", "Zeus"],
    [2, "Which game company created 'League of Legends'?", "Riot Games", "Blizzard", "Valve", "Epic Games"],
    [2, "What is the name of the villain in most Legend of Zelda games?", "Ganon", "Bowser", "Ridley", "Dark Link"],
    [2, "In 'Animal Crossing: New Horizons', who is the raccoon who runs things?", "Tom Nook", "Isabelle", "K.K. Slider", "Blathers"],
    [2, "What is the online store and launcher made by Valve?", "Steam", "Origin", "Uplay", "Battle.net"],
    [2, "Which game series features the Covenant and the Flood?", "Halo", "Mass Effect", "Destiny", "StarCraft"],
    [2, "In 'Overwatch', which hero is a time-jumping British adventurer?", "Tracer", "Widowmaker", "Mercy", "Sombra"],
    [2, "Which fighting game series is famous for 'Fatalities'?", "Mortal Kombat", "Street Fighter", "Tekken", "Soulcalibur"],
    [2, "What does 'RPG' stand for in gaming?", "Role-playing game", "Rapid player game", "Real progression game", "Ranged player gun"],
    [2, "Which game features the Battle Royale island known as 'Erangel'?", "PUBG: Battlegrounds", "Fortnite", "Apex Legends", "Free Fire"],
    [2, "What is the name of the fairy who helps Link in 'Ocarina of Time'?", "Navi", "Tatl", "Midna", "Fi"],
    [2, "Which game series stars Nathan Drake?", "Uncharted", "Tomb Raider", "The Last of Us", "Far Cry"],

    // Level 3 — Hard
    [3, "In what year was the original Nintendo Entertainment System released in North America?", "1985", "1983", "1988", "1990"],
    [3, "What was the first commercially successful video game, released by Atari in 1972?", "Pong", "Space Invaders", "Asteroids", "Breakout"],
    [3, "Which studio developed 'The Witcher 3: Wild Hunt'?", "CD Projekt Red", "BioWare", "Bethesda", "Ubisoft"],
    [3, "What is the name of the AI antagonist in 'Portal'?", "GLaDOS", "SHODAN", "Cortana", "HAL"],
    [3, "In 'The Last of Us', what is the name of the fungus that infects humans?", "Cordyceps", "Spores-X", "Mycelium", "The Bloom"],
    [3, "Which game company created 'Dark Souls'?", "FromSoftware", "Capcom", "Square Enix", "Bandai Namco"],
    [3, "What is the name of the princess in the original 'Donkey Kong' (1981)?", "Pauline", "Peach", "Daisy", "Rosalina"],
    [3, "Which Pokémon type is super effective against Water?", "Grass and Electric", "Fire", "Rock", "Ground"],
    [3, "Which game is set in the underwater city of Rapture?", "BioShock", "Subnautica", "Dead Space", "SOMA"],
    [3, "In 'Minecraft', what do you need to trade with villagers?", "Emeralds", "Diamonds", "Gold", "Iron"],
    [3, "Which Final Fantasy game introduced Cloud Strife?", "Final Fantasy VII", "Final Fantasy VI", "Final Fantasy VIII", "Final Fantasy X"],
    [3, "What year was 'World of Warcraft' released?", "2004", "2001", "2007", "2010"],
    [3, "In 'Super Mario Bros.', which world is the final world in the original game?", "World 8", "World 9", "World 7", "World 10"],
    [3, "Which game popularized the 'battle royale' genre in 2017 before Fortnite added its mode?", "PlayerUnknown's Battlegrounds", "H1Z1", "Apex Legends", "DayZ"],
    [3, "What is the name of the main character in 'Half-Life'?", "Gordon Freeman", "Alyx Vance", "Barney Calhoun", "Adrian Shephard"],
    [3, "Which handheld console introduced 'Pokémon Red and Blue' outside Japan?", "Game Boy", "Game Boy Advance", "Nintendo DS", "Game Gear"],
    [3, "Which company created 'Sonic the Hedgehog'?", "Sega", "Nintendo", "Capcom", "Namco"],
    [3, "What is the name of the original spaceship map in 'Among Us'?", "The Skeld", "Polus", "Mira HQ", "The Airship"],
    [3, "Which game series features the Animus device?", "Assassin's Creed", "Prince of Persia", "Splinter Cell", "Watch Dogs"],
    [3, "On which level does the original 'Pac-Man' famously glitch into a 'kill screen'?", "256", "100", "99", "128"],

    // Level 4 — Expert
    [4, "What was the code name of the Nintendo Wii during development?", "Revolution", "Dolphin", "Project Reality", "NX"],
    [4, "Which game designer created 'Super Mario Bros.' and 'The Legend of Zelda'?", "Shigeru Miyamoto", "Hideo Kojima", "Satoru Iwata", "Masahiro Sakurai"],
    [4, "What is the name of the hidden cheat code Up, Up, Down, Down, Left, Right, Left, Right, B, A?", "Konami Code", "Capcom Code", "Contra Code", "Nintendo Code"],
    [4, "Which 1980 arcade game's ghosts are named Blinky, Pinky, Inky and Clyde?", "Pac-Man", "Galaga", "Dig Dug", "Frogger"],
    [4, "Who created the 'Metal Gear' series?", "Hideo Kojima", "Shigeru Miyamoto", "Hironobu Sakaguchi", "Yu Suzuki"],
    [4, "What was Mario originally called in 'Donkey Kong' (1981)?", "Jumpman", "Mr. Video", "Carpenter", "Plumberman"],
    [4, "Which console was Sega's last home console?", "Dreamcast", "Saturn", "Genesis", "Master System"],
    [4, "In 'The Elder Scrolls V: Skyrim', what is the name of the main villain dragon?", "Alduin", "Paarthurnax", "Odahviing", "Mirmulnir"],
    [4, "Which company developed the 'Half-Life' series?", "Valve", "id Software", "Epic Games", "Bungie"],
    [4, "In 'Destiny', what is the name of the city protected by the Traveler?", "The Last City", "The Citadel", "The Tower City", "Reach"],
    [4, "Which game won The Game Awards' Game of the Year in 2022?", "Elden Ring", "God of War Ragnarök", "Horizon Forbidden West", "Stray"],
    [4, "What was the first video game console with interchangeable cartridges, released in 1976?", "Fairchild Channel F", "Atari 2600", "Magnavox Odyssey", "Intellivision"],
    [4, "In 'Dota 2', how many players are on each team?", "5", "4", "6", "3"],
    [4, "Which game introduced the character Lara Croft in 1996?", "Tomb Raider", "Uncharted", "Resident Evil", "Perfect Dark"],
    [4, "What is the name of the currency in 'The Legend of Zelda'?", "Rupees", "Gold", "Bells", "Gil"],
    [4, "Which Pokémon generation introduced the Fairy type?", "Generation VI (X and Y)", "Generation V", "Generation IV", "Generation VII"],
    [4, "In 'Super Smash Bros.', who is the series creator?", "Masahiro Sakurai", "Shigeru Miyamoto", "Koji Kondo", "Eiji Aonuma"],
    [4, "What is the name of the company in 'Resident Evil' responsible for the T-virus?", "Umbrella Corporation", "Aperture Science", "Black Mesa", "Abstergo"],
    [4, "What is the name of the main city in 'Grand Theft Auto IV'?", "Liberty City", "Vice City", "Los Santos", "San Fierro"],
    [4, "Who composed the classic 'Super Mario Bros.' theme?", "Koji Kondo", "Nobuo Uematsu", "Yoko Shimomura", "Akira Yamaoka"],
  ],
};
