'use strict';

module.exports = {
  category: "Geography",
  questions: [
    // Level 1 — Easy
    [1, "What is the capital of Japan?", "Tokyo", "Osaka", "Kyoto", "Seoul"],
    [1, "Which country is shaped like a boot?", "Italy", "Greece", "Portugal", "Chile"],
    [1, "What is the largest ocean on Earth?", "Pacific", "Atlantic", "Indian", "Arctic"],
    [1, "What is the capital of France?", "Paris", "Lyon", "Marseille", "Nice"],
    [1, "Which continent is Egypt in?", "Africa", "Asia", "Europe", "South America"],
    [1, "Which country has the Statue of Liberty?", "United States", "France", "Canada", "England"],
    [1, "What is the capital of England?", "London", "Manchester", "Liverpool", "Birmingham"],
    [1, "Which continent is the coldest?", "Antarctica", "Europe", "Asia", "North America"],
    [1, "Which country is home to kangaroos in the wild?", "Australia", "Brazil", "India", "South Africa"],
    [1, "The Amazon rainforest is mostly in which country?", "Brazil", "Mexico", "Peru", "Colombia"],
    [1, "Which country is directly north of the United States?", "Canada", "Mexico", "Russia", "Greenland"],
    [1, "What is the capital of Italy?", "Rome", "Milan", "Venice", "Naples"],
    [1, "Which continent is India part of?", "Asia", "Africa", "Europe", "Oceania"],
    [1, "In which country are the pyramids of Giza?", "Egypt", "Mexico", "Sudan", "Peru"],
    [1, "Which US state is made up entirely of islands?", "Hawaii", "Alaska", "Florida", "Rhode Island"],
    [1, "What is the capital of Spain?", "Madrid", "Barcelona", "Seville", "Valencia"],
    [1, "Which country is famous for maple syrup and the maple leaf flag?", "Canada", "Sweden", "Norway", "Switzerland"],
    [1, "Mount Fuji is in which country?", "Japan", "China", "South Korea", "Nepal"],
    [1, "Which city is known as the Big Apple?", "New York City", "Los Angeles", "Chicago", "Boston"],
    [1, "Which country has the most people in South America?", "Brazil", "Argentina", "Colombia", "Peru"],

    // Level 2 — Medium
    [2, "What is the capital of Australia?", "Canberra", "Sydney", "Melbourne", "Perth"],
    [2, "What is the capital of Canada?", "Ottawa", "Toronto", "Vancouver", "Montreal"],
    [2, "Which is the longest river in Africa?", "Nile", "Congo", "Niger", "Zambezi"],
    [2, "What is the smallest country in the world?", "Vatican City", "Monaco", "San Marino", "Liechtenstein"],
    [2, "Which desert is the largest hot desert?", "Sahara", "Gobi", "Kalahari", "Mojave"],
    [2, "What is the capital of Germany?", "Berlin", "Munich", "Frankfurt", "Hamburg"],
    [2, "What is the tallest mountain in the world above sea level?", "Mount Everest", "K2", "Kangchenjunga", "Denali"],
    [2, "Which river flows through London?", "Thames", "Seine", "Danube", "Rhine"],
    [2, "Which country has the largest land area?", "Russia", "Canada", "China", "United States"],
    [2, "What is the capital of Egypt?", "Cairo", "Alexandria", "Giza", "Luxor"],
    [2, "Which US state is the largest by area?", "Alaska", "Texas", "California", "Montana"],
    [2, "What is the capital of South Korea?", "Seoul", "Busan", "Incheon", "Pyongyang"],
    [2, "Which mountain range separates Europe and Asia in Russia?", "Ural Mountains", "Alps", "Himalayas", "Carpathians"],
    [2, "Which country has the city of Marrakesh?", "Morocco", "Tunisia", "Algeria", "Egypt"],
    [2, "Which ocean lies between Africa and Australia?", "Indian Ocean", "Pacific Ocean", "Atlantic Ocean", "Southern Ocean"],
    [2, "What is the capital of Argentina?", "Buenos Aires", "Santiago", "Montevideo", "Lima"],
    [2, "Which country is both in Europe and Asia and has Istanbul?", "Turkey", "Greece", "Iran", "Georgia"],
    [2, "Which African country has the largest population?", "Nigeria", "Egypt", "Ethiopia", "South Africa"],
    [2, "What is the largest island in the world?", "Greenland", "Australia", "Borneo", "Madagascar"],
    [2, "Venice is famous for its what?", "Canals", "Volcanoes", "Glaciers", "Deserts"],

    // Level 3 — Hard
    [3, "What is the capital of New Zealand?", "Wellington", "Auckland", "Christchurch", "Queenstown"],
    [3, "What is the capital of Turkey?", "Ankara", "Istanbul", "Izmir", "Antalya"],
    [3, "Which river is the longest in Europe?", "Volga", "Danube", "Rhine", "Dnieper"],
    [3, "What is the deepest point in the world's oceans?", "Challenger Deep", "Puerto Rico Trench", "Java Trench", "Tonga Trench"],
    [3, "Which country has the most natural lakes?", "Canada", "Russia", "Finland", "United States"],
    [3, "Which is the driest non-polar desert in the world?", "Atacama", "Sahara", "Gobi", "Namib"],
    [3, "What is the capital of Brazil?", "Brasília", "Rio de Janeiro", "São Paulo", "Salvador"],
    [3, "Lake Titicaca lies on the border of Peru and which country?", "Bolivia", "Chile", "Ecuador", "Brazil"],
    [3, "Which strait separates Europe and Africa?", "Strait of Gibraltar", "Strait of Hormuz", "Bosporus", "Strait of Messina"],
    [3, "What is the capital of Switzerland?", "Bern", "Zurich", "Geneva", "Basel"],
    [3, "Which country has the most islands in the world?", "Sweden", "Indonesia", "Philippines", "Norway"],
    [3, "The Danube river flows into which sea?", "Black Sea", "Mediterranean Sea", "Baltic Sea", "Adriatic Sea"],
    [3, "What is the capital of Vietnam?", "Hanoi", "Ho Chi Minh City", "Da Nang", "Hue"],
    [3, "Which is the largest country in Africa by area?", "Algeria", "Democratic Republic of the Congo", "Sudan", "Libya"],
    [3, "Which country is home to Angel Falls, the world's highest waterfall?", "Venezuela", "Brazil", "Guyana", "Colombia"],
    [3, "What is the capital of Morocco?", "Rabat", "Casablanca", "Marrakesh", "Fez"],
    [3, "Which sea is so salty that people float easily in it?", "Dead Sea", "Red Sea", "Caspian Sea", "Aral Sea"],
    [3, "Which country does the island of Sicily belong to?", "Italy", "Greece", "Malta", "Spain"],
    [3, "What is the largest lake in Africa?", "Lake Victoria", "Lake Tanganyika", "Lake Malawi", "Lake Chad"],
    [3, "Which line of latitude is at 0 degrees?", "Equator", "Tropic of Cancer", "Prime Meridian", "Arctic Circle"],

    // Level 4 — Expert
    [4, "What is the capital of Kazakhstan?", "Astana", "Almaty", "Bishkek", "Tashkent"],
    [4, "What is the capital of Myanmar?", "Naypyidaw", "Yangon", "Mandalay", "Bagan"],
    [4, "Which country has the longest coastline in the world?", "Canada", "Russia", "Indonesia", "Australia"],
    [4, "What is the only country that borders both the Atlantic and Indian Oceans directly, at the southern tip of Africa?", "South Africa", "Namibia", "Mozambique", "Angola"],
    [4, "Which landlocked country is entirely surrounded by South Africa?", "Lesotho", "Eswatini", "Botswana", "Zimbabwe"],
    [4, "What is the capital of Bhutan?", "Thimphu", "Kathmandu", "Paro", "Dhaka"],
    [4, "Which European capital lies on both banks of the Danube and was once two cities?", "Budapest", "Vienna", "Bratislava", "Belgrade"],
    [4, "What is the largest lake by area in the world?", "Caspian Sea", "Lake Superior", "Lake Victoria", "Lake Baikal"],
    [4, "What is the deepest lake in the world?", "Lake Baikal", "Lake Tanganyika", "Crater Lake", "Caspian Sea"],
    [4, "Which country has three capital cities: Pretoria, Cape Town and Bloemfontein?", "South Africa", "Namibia", "Botswana", "Zimbabwe"],
    [4, "What is the capital of Mongolia?", "Ulaanbaatar", "Astana", "Bishkek", "Hohhot"],
    [4, "Which two countries share the world's longest international land border?", "Canada and the United States", "Russia and Kazakhstan", "Argentina and Chile", "China and Mongolia"],
    [4, "The Atacama Desert is mainly in which country?", "Chile", "Peru", "Argentina", "Bolivia"],
    [4, "Which microstate is located between France and Spain in the Pyrenees?", "Andorra", "Monaco", "San Marino", "Liechtenstein"],
    [4, "What is the capital of Nigeria?", "Abuja", "Lagos", "Kano", "Ibadan"],
    [4, "Which country's flag is the only non-rectangular national flag?", "Nepal", "Switzerland", "Bhutan", "Vatican City"],
    [4, "Which river flows through Baghdad?", "Tigris", "Euphrates", "Jordan", "Nile"],
    [4, "What is the highest mountain in Africa?", "Mount Kilimanjaro", "Mount Kenya", "Mount Stanley", "Ras Dashen"],
    [4, "What is the capital of Canada's province of British Columbia?", "Victoria", "Vancouver", "Kelowna", "Surrey"],
    [4, "Which country is known as the 'Land of a Thousand Lakes' (it actually has far more)?", "Finland", "Sweden", "Canada", "Norway"],
  ],
};
