'use strict';

module.exports = {
  category: "History",
  questions: [
    // Level 1 — Easy
    [1, "Who was the first President of the United States?", "George Washington", "Thomas Jefferson", "Abraham Lincoln", "John Adams"],
    [1, "Which ancient civilization built the pyramids of Giza?", "Egyptians", "Romans", "Greeks", "Mayans"],
    [1, "In what year did humans first land on the Moon?", "1969", "1965", "1972", "1959"],
    [1, "Which country gifted the Statue of Liberty to the USA?", "France", "England", "Spain", "Italy"],
    [1, "Who was the first person to walk on the Moon?", "Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "John Glenn"],
    [1, "Which empire was ruled by Julius Caesar?", "Roman", "Ottoman", "Persian", "Mongol"],
    [1, "What ship carried the Pilgrims to America in 1620?", "Mayflower", "Santa Maria", "Endeavour", "Beagle"],
    [1, "Which explorer sailed to the Americas in 1492?", "Christopher Columbus", "Vasco da Gama", "Ferdinand Magellan", "James Cook"],
    [1, "The Great Wall was built in which country?", "China", "Japan", "India", "Mongolia"],
    [1, "Who was the U.S. president during the Civil War?", "Abraham Lincoln", "George Washington", "Ulysses S. Grant", "Andrew Jackson"],
    [1, "Which famous queen of Egypt was linked to Mark Antony?", "Cleopatra", "Nefertiti", "Hatshepsut", "Isis"],
    [1, "Knights in shining armor are most associated with which period?", "Middle Ages", "Stone Age", "Industrial Revolution", "Space Age"],
    [1, "What were the giant reptiles that lived millions of years ago called?", "Dinosaurs", "Mammoths", "Sabertooths", "Dodos"],
    [1, "Which country was ruled by pharaohs?", "Egypt", "Greece", "Persia", "Rome"],
    [1, "In which city is the Colosseum located?", "Rome", "Athens", "Paris", "Istanbul"],
    [1, "What did the Wright brothers invent?", "The first powered airplane", "The telephone", "The car", "The light bulb"],
    [1, "Who is famous for the 'I Have a Dream' speech?", "Martin Luther King Jr.", "Malcolm X", "Barack Obama", "Rosa Parks"],
    [1, "Which people were famous for longships and raiding across Europe?", "Vikings", "Romans", "Aztecs", "Samurai"],
    [1, "In which country did the Olympic Games originate?", "Greece", "Italy", "Egypt", "France"],
    [1, "Who invented the light bulb, according to the popular story?", "Thomas Edison", "Nikola Tesla", "Alexander Graham Bell", "Benjamin Franklin"],

    // Level 2 — Medium
    [2, "In what year did World War II end?", "1945", "1939", "1944", "1950"],
    [2, "Which wall fell in 1989?", "Berlin Wall", "Great Wall", "Hadrian's Wall", "Western Wall"],
    [2, "The Titanic sank in which year?", "1912", "1905", "1920", "1898"],
    [2, "Who was the main author of the Declaration of Independence?", "Thomas Jefferson", "Benjamin Franklin", "John Hancock", "James Madison"],
    [2, "Who was known as the Maid of Orléans?", "Joan of Arc", "Marie Antoinette", "Catherine de' Medici", "Eleanor of Aquitaine"],
    [2, "In what year did World War I begin?", "1914", "1912", "1916", "1918"],
    [2, "Who was the first emperor of France?", "Napoleon Bonaparte", "Louis XIV", "Charlemagne", "Louis XVI"],
    [2, "Which civilization built Machu Picchu?", "Inca", "Aztec", "Maya", "Olmec"],
    [2, "Who was the British prime minister for most of World War II?", "Winston Churchill", "Neville Chamberlain", "Clement Attlee", "Margaret Thatcher"],
    [2, "In what year did the United States declare independence?", "1776", "1789", "1765", "1812"],
    [2, "Which city was destroyed by Mount Vesuvius in 79 AD?", "Pompeii", "Athens", "Carthage", "Troy"],
    [2, "Who was the first woman to fly solo across the Atlantic?", "Amelia Earhart", "Bessie Coleman", "Harriet Quimby", "Jacqueline Cochran"],
    [2, "The Renaissance began in which country?", "Italy", "France", "England", "Spain"],
    [2, "Who was the leader of the Soviet Union during World War II?", "Joseph Stalin", "Vladimir Lenin", "Nikita Khrushchev", "Leon Trotsky"],
    [2, "Which document was signed in 1215 limiting the English king's power?", "Magna Carta", "Bill of Rights", "Domesday Book", "Act of Union"],
    [2, "Who was the first female Prime Minister of the United Kingdom?", "Margaret Thatcher", "Theresa May", "Queen Victoria", "Indira Gandhi"],
    [2, "What was the name of the first human in space?", "Yuri Gagarin", "Alan Shepard", "John Glenn", "Valentina Tereshkova"],
    [2, "Which U.S. president was assassinated in 1963?", "John F. Kennedy", "Abraham Lincoln", "William McKinley", "Richard Nixon"],
    [2, "Who led India's non-violent independence movement?", "Mahatma Gandhi", "Jawaharlal Nehru", "Subhas Chandra Bose", "B. R. Ambedkar"],
    [2, "What was the name of the trade route connecting China to the Mediterranean?", "Silk Road", "Spice Way", "Amber Road", "Tea Trail"],

    // Level 3 — Hard
    [3, "In what year did the French Revolution begin?", "1789", "1776", "1799", "1804"],
    [3, "Who was the first emperor of unified China?", "Qin Shi Huang", "Kublai Khan", "Sun Yat-sen", "Emperor Wu"],
    [3, "Which battle in 1815 marked Napoleon's final defeat?", "Waterloo", "Austerlitz", "Trafalgar", "Leipzig"],
    [3, "Which empire was ruled from Constantinople after the fall of Rome in the West?", "Byzantine Empire", "Ottoman Empire", "Holy Roman Empire", "Persian Empire"],
    [3, "Who was the longest-reigning British monarch?", "Elizabeth II", "Victoria", "George III", "Henry VIII"],
    [3, "Which country was the first to adopt Christianity as its state religion, in 301 AD?", "Armenia", "Roman Empire", "Ethiopia", "Georgia"],
    [3, "Who wrote 'The Communist Manifesto' with Karl Marx?", "Friedrich Engels", "Vladimir Lenin", "Leon Trotsky", "Adam Smith"],
    [3, "Which Mongol leader founded the largest contiguous land empire in history?", "Genghis Khan", "Kublai Khan", "Attila", "Tamerlane"],
    [3, "The Hundred Years' War was fought mainly between which two countries?", "England and France", "Spain and Portugal", "France and Spain", "England and Scotland"],
    [3, "Which ancient wonder was located in Alexandria?", "The Lighthouse (Pharos)", "The Hanging Gardens", "The Colossus", "The Mausoleum"],
    [3, "Who was the first Black president of South Africa?", "Nelson Mandela", "Thabo Mbeki", "Desmond Tutu", "Jacob Zuma"],
    [3, "Which treaty officially ended World War I with Germany?", "Treaty of Versailles", "Treaty of Paris", "Treaty of Ghent", "Treaty of Tordesillas"],
    [3, "In which year did the Soviet Union dissolve?", "1991", "1989", "1993", "1985"],
    [3, "Which explorer's expedition first circumnavigated the globe?", "Ferdinand Magellan", "Francis Drake", "James Cook", "Vasco da Gama"],
    [3, "What was the name of the U.S. program that landed humans on the Moon?", "Apollo", "Gemini", "Mercury", "Artemis"],
    [3, "Who was the Greek conqueror who created an empire stretching to India?", "Alexander the Great", "Pericles", "Leonidas", "Philip II"],
    [3, "The Cuban Missile Crisis took place in which year?", "1962", "1959", "1965", "1968"],
    [3, "Which dynasty built most of the Great Wall that stands today?", "Ming", "Qin", "Han", "Tang"],
    [3, "Who was the first female pharaoh to rule Egypt with full powers for a long reign?", "Hatshepsut", "Cleopatra", "Nefertiti", "Nefertari"],
    [3, "What ancient city-state was famous for its warrior culture and King Leonidas?", "Sparta", "Athens", "Corinth", "Thebes"],

    // Level 4 — Expert
    [4, "In what year was the Battle of Hastings?", "1066", "1088", "1016", "1215"],
    [4, "Which Roman emperor made Christianity legal with the Edict of Milan?", "Constantine", "Nero", "Augustus", "Diocletian"],
    [4, "What was the capital of the Aztec Empire?", "Tenochtitlan", "Cusco", "Chichen Itza", "Teotihuacan"],
    [4, "Who was the last tsar of Russia?", "Nicholas II", "Alexander III", "Peter the Great", "Ivan IV"],
    [4, "The Peace of Westphalia in 1648 ended which war?", "Thirty Years' War", "Hundred Years' War", "Seven Years' War", "War of the Roses"],
    [4, "Which Carthaginian general crossed the Alps with elephants?", "Hannibal", "Hamilcar", "Scipio", "Hasdrubal"],
    [4, "Who was the first Holy Roman Emperor, crowned in 800 AD?", "Charlemagne", "Otto I", "Frederick Barbarossa", "Charles V"],
    [4, "In what year did Constantinople fall to the Ottomans?", "1453", "1492", "1204", "1517"],
    [4, "Which pharaoh's nearly intact tomb was discovered by Howard Carter in 1922?", "Tutankhamun", "Ramesses II", "Khufu", "Akhenaten"],
    [4, "What was the name of the 1494 treaty that divided new lands between Spain and Portugal?", "Treaty of Tordesillas", "Treaty of Utrecht", "Treaty of Seville", "Treaty of Lisbon"],
    [4, "Which English king had six wives?", "Henry VIII", "Edward VI", "Richard III", "Henry VII"],
    [4, "What was the name of the ancient Mesopotamian code of law from around 1754 BC?", "Code of Hammurabi", "Code of Justinian", "Laws of Solon", "Twelve Tables"],
    [4, "Who was the founder of the Achaemenid Persian Empire?", "Cyrus the Great", "Darius I", "Xerxes I", "Cambyses II"],
    [4, "Which war was fought between the Houses of Lancaster and York?", "Wars of the Roses", "Hundred Years' War", "English Civil War", "Glorious Revolution"],
    [4, "The Meiji Restoration modernized which country in 1868?", "Japan", "China", "Korea", "Thailand"],
    [4, "Who was the leader of the Haitian Revolution?", "Toussaint Louverture", "Simón Bolívar", "Jean-Jacques Dessalines", "José de San Martín"],
    [4, "What ancient trade city in Jordan is carved into rose-red cliffs?", "Petra", "Palmyra", "Jerash", "Babylon"],
    [4, "Which 1648-1653 French civil wars were named after a children's sling game?", "The Fronde", "The Huguenot Wars", "The Jacquerie", "The Vendée"],
    [4, "The Rosetta Stone helped scholars decipher which writing system?", "Egyptian hieroglyphs", "Cuneiform", "Linear B", "Mayan glyphs"],
    [4, "Which South American liberator was known as 'El Libertador'?", "Simón Bolívar", "José de San Martín", "Bernardo O'Higgins", "Antonio José de Sucre"],
  ],
};
