'use strict';

module.exports = {
  category: "Internet Culture",
  questions: [
    // Level 1 — Easy
    [1, "What does 'LOL' stand for?", "Laugh out loud", "Lots of love", "Lack of luck", "Look out loud"],
    [1, "What does 'IRL' mean?", "In real life", "I really laughed", "Instant reply later", "In random lobby"],
    [1, "What does 'AFK' stand for?", "Away from keyboard", "Always feeling kind", "Ask for keys", "Another fun kill"],
    [1, "What does 'GOAT' stand for in slang?", "Greatest of all time", "Going out all tonight", "Good old American tradition", "Game over, ask twice"],
    [1, "What do you call a funny image or idea that spreads online?", "Meme", "Blog", "Podcast", "Spam"],
    [1, "Which platform popularized the short vertical 'For You' feed?", "TikTok", "Vine", "Snapchat", "Tumblr"],
    [1, "What symbol is used to start a hashtag?", "#", "@", "&", "$"],
    [1, "What does 'BRB' stand for?", "Be right back", "Bring real bread", "Big red button", "Back row baby"],
    [1, "Which website is mostly used to watch and upload videos?", "YouTube", "Wikipedia", "Amazon", "LinkedIn"],
    [1, "What does 'DM' mean on social media?", "Direct message", "Data mode", "Daily meme", "Do more"],
    [1, "What is someone who live-streams games on Twitch usually called?", "Streamer", "Lurker", "Modder", "Blogger"],
    [1, "What does 'OMG' stand for?", "Oh my god", "One more game", "Only my gaming", "Online meme group"],
    [1, "What is the '@' symbol used for on social media?", "Mentioning or tagging a user", "Starting a hashtag", "Liking a post", "Deleting a post"],
    [1, "What does 'TBH' mean?", "To be honest", "Too bad, honey", "Text back home", "The big hit"],
    [1, "Which app is known for disappearing photo messages and a ghost logo?", "Snapchat", "Instagram", "WhatsApp", "Telegram"],
    [1, "What do you call it when a post spreads extremely fast online?", "Going viral", "Going dark", "Going offline", "Going private"],
    [1, "What does 'NPC' stand for?", "Non-player character", "New player club", "No points counted", "Never play casual"],
    [1, "What is a 'selfie'?", "A photo you take of yourself", "A video game", "A type of emoji", "A private message"],
    [1, "What does 'FOMO' stand for?", "Fear of missing out", "Friends online, me offline", "Find out more online", "Fast online mode"],
    [1, "In slang, 'mogging' someone means you…", "Outshine them", "Ignore them", "Copy them", "Block them"],

    // Level 2 — Medium
    [2, "The famous Omegle tagline was 'Talk to ___!'", "strangers", "friends", "anyone", "robots"],
    [2, "'Rickrolling' uses a song by which artist?", "Rick Astley", "Rick James", "Rick Ross", "Rick Springfield"],
    [2, "What animal is the 'Doge' meme?", "Shiba Inu", "Corgi", "Husky", "Akita"],
    [2, "Which website is known as 'the front page of the internet'?", "Reddit", "Digg", "Yahoo", "Tumblr"],
    [2, "'NPC' as an insult originally comes from which field?", "Video games", "Film", "Politics", "Sports"],
    [2, "What does 'TL;DR' stand for?", "Too long; didn't read", "Total loss; don't retry", "Try later; done reading", "Text lost; data removed"],
    [2, "Which short-video app shut down in 2017 and had six-second loops?", "Vine", "Musical.ly", "Periscope", "Dubsmash"],
    [2, "What does it mean to 'ratio' someone on social media?", "Your reply gets more likes than their post", "You block them", "You copy their post", "You report them"],
    [2, "What does the slang 'cap' mean?", "A lie", "A hat compliment", "The truth", "Something expensive"],
    [2, "Which bird was the original logo of Twitter?", "A bluebird", "A parrot", "An eagle", "A robin"],
    [2, "What does 'POV' stand for in TikTok captions?", "Point of view", "Post of value", "Proof of video", "People on video"],
    [2, "Which platform is Twitch owned by?", "Amazon", "Google", "Meta", "Microsoft"],
    [2, "What does 'IMO' stand for?", "In my opinion", "In many options", "I miss oranges", "Instant message online"],
    [2, "What's the name of the frog meme associated with 'feels good man'?", "Pepe the Frog", "Kermit", "Freddie", "Froggy Fresh"],
    [2, "What does 'stan' mean in internet slang?", "An extremely devoted fan", "A hater", "A bot account", "A moderator"],
    [2, "What does 'NGL' mean in texts?", "Not gonna lie", "Never give lessons", "No good luck", "Next game later"],
    [2, "What does it mean when someone says 'it's giving'?", "It has a certain vibe", "It's free", "It's broken", "It's raining"],
    [2, "What do gamers mean by 'GG'?", "Good game", "Get going", "Great gun", "Give gold"],
    [2, "What is 'clickbait'?", "A misleading headline designed to get clicks", "A computer virus", "A paid ad", "A popular video"],
    [2, "What does 'sus' mean, popularized by Among Us?", "Suspicious", "Super", "Sustainable", "Sweet"],

    // Level 3 — Hard
    [3, "In what year was YouTube founded?", "2005", "2003", "2007", "2009"],
    [3, "What was the first video ever uploaded to YouTube called?", "Me at the zoo", "Charlie bit my finger", "Hello World", "Evolution of Dance"],
    [3, "Which meme features a man looking back at another woman while his girlfriend looks shocked?", "Distracted Boyfriend", "Hide the Pain Harold", "Drakeposting", "Woman Yelling at Cat"],
    [3, "What year was Facebook launched?", "2004", "2006", "2002", "2008"],
    [3, "What is the name of the grumpy-faced cat that became a meme in 2012?", "Grumpy Cat", "Keyboard Cat", "Nyan Cat", "Longcat"],
    [3, "In what year did Nyan Cat go viral?", "2011", "2009", "2013", "2015"],
    [3, "Which 2012 song became the first YouTube video to hit 1 billion views?", "Gangnam Style", "Baby", "Despacito", "Call Me Maybe"],
    [3, "What does 'ELI5' mean on Reddit?", "Explain like I'm five", "Everyone loves it, 5 stars", "Exit lobby in 5", "Edit later in 5 minutes"],
    [3, "Which early viral YouTube video shows a baby biting his brother's finger?", "Charlie Bit My Finger", "Me at the zoo", "Sneezing Baby Panda", "Evolution of Dance"],
    [3, "What is the name of the meme of a dog sitting in a burning room saying 'This is fine'?", "This Is Fine", "Doge", "Cheems", "Walter"],
    [3, "What is a 'Streisand effect'?", "Trying to hide something makes it more famous", "A song going viral", "A celebrity deleting an account", "A video being demonetized"],
    [3, "Which platform was originally called 'Thefacebook'?", "Facebook", "MySpace", "Friendster", "Instagram"],
    [3, "What was the original name of TikTok's predecessor app, merged in 2018?", "Musical.ly", "Vine", "Dubsmash", "Triller"],
    [3, "What does 'ASMR' stand for?", "Autonomous sensory meridian response", "Audio sound media recording", "Automatic speech meme reaction", "Ambient sound mood relaxation"],
    [3, "Who created the Omegle website in 2009?", "Leif K-Brooks", "Mark Zuckerberg", "Chris Poole", "Kevin Systrom"],
    [3, "What does 'OP' mean in a forum thread?", "Original poster", "Overpowered post", "Online person", "Open post"],
    [3, "What does the 'Woman Yelling at Cat' meme pair together?", "A reality TV scene and a cat at a dinner table", "Two cats", "A dog and a cat", "A movie scene and a frog"],
    [3, "Which year did Omegle shut down?", "2023", "2021", "2019", "2024"],
    [3, "What is a 'copypasta'?", "A block of text copied and pasted repeatedly online", "A type of pasta recipe", "A computer error", "A viral video"],
    [3, "What does telling someone to 'touch grass' mean?", "Go outside and spend less time online", "Start gardening", "Play a sports game", "Log in to a new app"],

    // Level 4 — Expert
    [4, "What year was the first email sent, by Ray Tomlinson?", "1971", "1965", "1983", "1990"],
    [4, "What misspelled lolcat caption from 2007 became the name of a famous meme site?", "I Can Has Cheezburger?", "Ceiling Cat Is Watching", "Invisible Bicycle", "Oh Hai"],
    [4, "What is the name of the 2000s flash animation featuring a dancing banana singing about peanut butter jelly time?", "Peanut Butter Jelly Time", "Badger Badger Badger", "Llama Song", "The End of the World"],
    [4, "Which emoticon was proposed by Scott Fahlman in 1982 to mark jokes?", ":-)", ":D", "<3", ";)"],
    [4, "What does 'Godwin's law' say about online arguments?", "They eventually compare someone to Hitler or Nazis", "They always end with a meme", "They go off-topic within 10 replies", "The loudest person wins"],
    [4, "What was the first domain name ever registered, in 1985?", "symbolics.com", "google.com", "apple.com", "ibm.com"],
    [4, "What is 'Poe's law'?", "Extreme views online are hard to tell apart from parody without clear signals", "Every meme dies in a year", "Comments are always negative", "Anonymous users are always trolls"],
    [4, "Which 2010 song had a viral 'Friday, Friday, gotta get down on Friday' chorus?", "Friday by Rebecca Black", "Friday by Riton", "Friday I'm in Love by The Cure", "TGIF by Katy Perry"],
    [4, "In online communities, what is a 'lurker'?", "Someone who reads but rarely posts", "A hacker", "A moderator", "A bot account"],
    [4, "The 'Harlem Shake' meme took off in which year?", "2013", "2011", "2015", "2009"],
    [4, "What was the name of Google's social network that shut down in 2019?", "Google+", "Google Wave", "Orkut", "Buzz"],
    [4, "In 'World of Warcraft', what did a Horde player's 'lol' appear as to Alliance players?", "kek", "bur", "lul", "omg"],
    [4, "What was MySpace's famous default first 'friend' called?", "Tom", "Steve", "Mark", "John"],
    [4, "What was the name of the 2011 internet trend of lying face down in odd places?", "Planking", "Owling", "Tebowing", "Dabbing"],
    [4, "Which meme cat appears with a Pop-Tart body flying through space?", "Nyan Cat", "Grumpy Cat", "Keyboard Cat", "Longcat"],
    [4, "In what year was Twitter rebranded as X?", "2023", "2022", "2021", "2024"],
    [4, "Which 2010 viral video features a man overjoyed by a rainbow 'all the way across the sky'?", "Double Rainbow", "Charlie Bit My Finger", "Chocolate Rain", "Leave Britney Alone"],
    [4, "Which site popularized 'advice animals' and rage comics in the late 2000s alongside Reddit?", "4chan", "LinkedIn", "Friendster", "Bebo"],
    [4, "What is the meaning of the acronym 'IIRC'?", "If I recall correctly", "I'm in real chat", "Internet relay chat", "If it's really cool"],
    [4, "Which 1990s chat system used 'channels' starting with '#'?", "IRC", "AIM", "ICQ", "MSN Messenger"],
  ],
};
