'use strict';

module.exports = {
  category: "Language & Words",
  questions: [
    // Level 1 — Easy
    [1, "What is the opposite of 'hot'?", "Cold", "Warm", "Spicy", "Wet"],
    [1, "How do you say 'hello' in Spanish?", "Hola", "Bonjour", "Ciao", "Hallo"],
    [1, "Which word is a noun?", "Table", "Run", "Quickly", "Blue"],
    [1, "What is the plural of 'child'?", "Children", "Childs", "Childes", "Childen"],
    [1, "How do you say 'thank you' in French?", "Merci", "Gracias", "Danke", "Grazie"],
    [1, "Which letter is a vowel?", "E", "B", "T", "K"],
    [1, "What is a word that means the same as 'happy'?", "Joyful", "Sad", "Angry", "Tired"],
    [1, "What punctuation mark ends a question?", "Question mark", "Period", "Comma", "Colon"],
    [1, "Which word rhymes with 'cat'?", "Hat", "Dog", "Cut", "Cap"],
    [1, "What is the opposite of 'up'?", "Down", "Over", "Under", "Out"],
    [1, "How do you say 'goodbye' in Italian (informal)?", "Ciao", "Adiós", "Au revoir", "Tschüss"],
    [1, "What is the past tense of 'go'?", "Went", "Goed", "Gone", "Going"],
    [1, "Which word is a verb?", "Jump", "Chair", "Green", "Happy"],
    [1, "What is the first letter of the alphabet?", "A", "B", "Z", "E"],
    [1, "Which language is mainly spoken in Brazil?", "Portuguese", "Spanish", "English", "French"],
    [1, "What is a baby's word for mother in English?", "Mama", "Papa", "Nana", "Dada"],
    [1, "How many vowels are in the English alphabet (not counting Y)?", "5", "6", "4", "7"],
    [1, "What is the opposite of 'big'?", "Small", "Tall", "Wide", "Huge"],
    [1, "Which word is spelled correctly?", "Friend", "Freind", "Frend", "Friennd"],
    [1, "What do you call a word that describes a noun?", "Adjective", "Verb", "Adverb", "Pronoun"],

    // Level 2 — Medium
    [2, "What is an 'anagram'?", "A word made by rearranging another word's letters", "A word that reads the same backward", "A word with two meanings", "A shortened word"],
    [2, "What does the prefix 'un-' usually mean?", "Not", "Again", "Before", "Very"],
    [2, "What does the French word 'chat' mean?", "Cat", "Talk", "Hat", "Dog"],
    [2, "What is the Spanish word for 'water'?", "Agua", "Eau", "Acqua", "Wasser"],
    [2, "What is a synonym for 'enormous'?", "Huge", "Tiny", "Average", "Narrow"],
    [2, "What is the German word for 'thank you'?", "Danke", "Bitte", "Gracias", "Merci"],
    [2, "What type of word is 'quickly'?", "Adverb", "Adjective", "Noun", "Verb"],
    [2, "What does 'bonjour' mean in English?", "Good day / hello", "Good night", "Goodbye", "Thank you"],
    [2, "Which word is an antonym of 'generous'?", "Stingy", "Kind", "Giving", "Charitable"],
    [2, "What is an 'acronym'?", "A word formed from initial letters, like NASA", "A word that sounds like another", "A word with opposite meaning", "A very long word"],
    [2, "What does the Spanish word 'gato' mean?", "Cat", "Dog", "Cake", "Hat"],
    [2, "What is the plural of 'cactus' (traditional)?", "Cacti", "Cactuses only", "Cactae", "Cactis"],
    [2, "What language does the word 'kindergarten' come from?", "German", "Dutch", "French", "Swedish"],
    [2, "Which word is a homophone of 'their'?", "There", "Then", "Three", "Tire"],
    [2, "What is the Japanese word for 'thank you' (common form)?", "Arigatō", "Konnichiwa", "Sayōnara", "Sumimasen"],
    [2, "What does 'RSVP' come from?", "French: répondez s'il vous plaît", "Latin: rogo si vales placere", "Italian: rispondi se vuoi", "English: reply soon, very please"],
    [2, "What is the Italian word for a male 'friend'?", "Amico", "Amigo", "Ami", "Freund"],
    [2, "Which is the correct spelling?", "Necessary", "Neccessary", "Necesary", "Neccesary"],
    [2, "What is a group of words containing a subject and a verb called?", "Clause", "Phrase only", "Prefix", "Syllable"],
    [2, "Which word means 'a fear of spiders'?", "Arachnophobia", "Agoraphobia", "Claustrophobia", "Acrophobia"],

    // Level 3 — Hard
    [3, "The English word 'amok' (as in 'run amok') comes from which language?", "Malay", "Hindi", "Arabic", "Swahili"],
    [3, "What is an 'oxymoron'?", "A phrase with contradictory words, like 'jumbo shrimp'", "A very long word", "A rhyming phrase", "A made-up word"],
    [3, "The English word 'tsunami' comes from which language?", "Japanese", "Chinese", "Hawaiian", "Malay"],
    [3, "What does the Latin phrase 'carpe diem' mean?", "Seize the day", "Love conquers all", "I came, I saw", "Know yourself"],
    [3, "What is a 'pangram'?", "A sentence using every letter of the alphabet", "A word that reads the same backward", "A poem with no rhymes", "A sentence with no verbs"],
    [3, "Which word is the onomatopoeia?", "Buzz", "Quiet", "Light", "Happy"],
    [3, "What does 'déjà vu' literally mean in French?", "Already seen", "Never again", "Dream memory", "Seen tomorrow"],
    [3, "What is the official language of Iran?", "Persian (Farsi)", "Arabic", "Turkish", "Urdu"],
    [3, "What is a 'haiku'?", "A three-line Japanese poem of 5-7-5 syllables", "A 14-line poem", "A song chorus", "A rhyming couplet"],
    [3, "How many lines does a sonnet have?", "14", "12", "10", "16"],
    [3, "What does the suffix '-ology' mean?", "The study of", "Fear of", "Love of", "Lack of"],
    [3, "The word 'robot' comes from which language?", "Czech", "Russian", "German", "Japanese"],
    [3, "What is the term for words that have the same spelling but different meanings, like 'bat' and 'bat'?", "Homonyms", "Synonyms", "Antonyms", "Acronyms"],
    [3, "Which alphabet is used to write Russian?", "Cyrillic", "Latin", "Greek", "Arabic"],
    [3, "What does 'ad hoc' mean?", "For this specific purpose", "After death", "To infinity", "In good faith"],
    [3, "What is the most commonly used letter in English?", "E", "A", "T", "S"],
    [3, "What does the abbreviation 'e.g.' stand for?", "Exempli gratia (for example)", "Et genus (and kind)", "Ergo generalis", "Extra good"],
    [3, "What is a 'portmanteau' word?", "A blend of two words, like 'brunch'", "A word borrowed from French", "A word that sounds like its meaning", "A word with no vowels"],
    [3, "Which language is Hindi most closely related to?", "Urdu", "Tamil", "Bengali", "Punjabi"],
    [3, "Which language do the most people in Switzerland speak as their main language?", "German", "French", "Italian", "Romansh"],

    // Level 4 — Expert
    [4, "What does the Latin phrase 'veni, vidi, vici' mean?", "I came, I saw, I conquered", "I lived, I loved, I lost", "I saw, I won, I left", "I came, I fought, I died"],
    [4, "Which common English word ends in the letters 'mt'?", "Dreamt", "Unkempt", "Attempt", "Exempt"],
    [4, "What is the study of the origin of words called?", "Etymology", "Entomology", "Phonology", "Morphology"],
    [4, "What is a 'shibboleth'?", "A word or custom that identifies members of a group", "A Hebrew prayer", "A type of poem", "A grammar mistake"],
    [4, "What does 'i.e.' stand for?", "Id est (that is)", "In example", "Ita est", "Inter alia"],
    [4, "Which language isolate is spoken in parts of Spain and France?", "Basque", "Catalan", "Galician", "Occitan"],
    [4, "What is the name for the '&' symbol?", "Ampersand", "Asterisk", "Octothorpe", "Pilcrow"],
    [4, "What is the symbol '¶' called?", "Pilcrow", "Section sign", "Dagger", "Caret"],
    [4, "What does the word 'sesquipedalian' describe?", "Using long words", "Having six legs", "Speaking slowly", "Being very tall"],
    [4, "What is 'litotes'?", "Understatement using a negative, like 'not bad'", "Exaggeration for effect", "Repeating a word", "A comparison using 'like'"],
    [4, "What does the Latin phrase 'in vino veritas' mean?", "In wine, there is truth", "Wine is life", "Truth grows on the vine", "Wine brings victory"],
    [4, "What does the Greek root 'chrono' mean?", "Time", "Color", "Light", "Life"],
    [4, "What is a 'lipogram'?", "Writing that avoids a particular letter", "A poem about lips", "A palindrome sentence", "A misspelled word"],
    [4, "The French novel 'La Disparition' famously avoids which letter?", "E", "A", "S", "T"],
    [4, "What is the term for a word formed by reversing another word, like 'stressed' and 'desserts'?", "Semordnilap", "Palindrome", "Anagram", "Spoonerism"],
    [4, "What is a 'spoonerism'?", "Swapping sounds between words, like 'tease my ears' for 'ease my tears'", "A word blend", "A kitchen term", "A rhyming slang"],
    [4, "Which writing system uses 'hiragana', 'katakana' and 'kanji'?", "Japanese", "Korean", "Chinese", "Thai"],
    [4, "What is the Korean alphabet called?", "Hangul", "Hanzi", "Kana", "Devanagari"],
    [4, "What is the term for the repetition of initial consonant sounds, like 'Peter Piper picked'?", "Alliteration", "Assonance", "Consonance", "Onomatopoeia"],
    [4, "What does 'per se' mean?", "By itself / intrinsically", "Per second", "For example", "In person"],
  ],
};
