'use strict';

module.exports = {
  category: "Literature",
  questions: [
    // Level 1 — Easy
    [1, "Who wrote the Harry Potter books?", "J.K. Rowling", "Roald Dahl", "C.S. Lewis", "Rick Riordan"],
    [1, "What kind of animal is Winnie-the-Pooh?", "Bear", "Pig", "Rabbit", "Tiger"],
    [1, "Which character says 'To be, or not to be'?", "Hamlet", "Romeo", "Macbeth", "Othello"],
    [1, "In 'The Cat in the Hat', who is the author?", "Dr. Seuss", "Shel Silverstein", "Maurice Sendak", "Eric Carle"],
    [1, "What is the name of the boy who never grows up?", "Peter Pan", "Pinocchio", "Oliver Twist", "Tom Sawyer"],
    [1, "Which fairy tale features a glass slipper?", "Cinderella", "Snow White", "Rapunzel", "Sleeping Beauty"],
    [1, "Which puppet's nose grows when he lies?", "Pinocchio", "Howdy Doody", "Punch", "Kermit"],
    [1, "In 'Charlotte's Web', what kind of animal is Charlotte?", "Spider", "Pig", "Goose", "Rat"],
    [1, "Which girl falls down a rabbit hole into Wonderland?", "Alice", "Dorothy", "Wendy", "Matilda"],
    [1, "Which detective lives at 221B Baker Street?", "Sherlock Holmes", "Hercule Poirot", "Miss Marple", "Nancy Drew"],
    [1, "In 'The Very Hungry Caterpillar', what does the caterpillar become?", "A butterfly", "A moth", "A bee", "A ladybug"],
    [1, "Who wrote 'Romeo and Juliet'?", "William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain"],
    [1, "What city lies at the end of the yellow brick road?", "The Emerald City", "Gold City", "Ruby City", "Crystal City"],
    [1, "Which fairy tale character lets down her long hair from a tower?", "Rapunzel", "Belle", "Ariel", "Goldilocks"],
    [1, "In 'Goldilocks', how many bears are there?", "3", "2", "4", "7"],
    [1, "Which school does Harry Potter attend?", "Hogwarts", "Durmstrang", "Beauxbatons", "Brakebills"],
    [1, "Who is Sherlock Holmes's assistant?", "Dr. Watson", "Inspector Lestrade", "Moriarty", "Mycroft"],
    [1, "What is a book of maps called?", "Atlas", "Dictionary", "Encyclopedia", "Almanac"],
    [1, "What does a dictionary mainly contain?", "Word definitions", "Maps", "Recipes", "Poems"],
    [1, "Which wolf tricks a girl in a red hood?", "The Big Bad Wolf", "White Fang", "Akela", "Fenrir"],

    // Level 2 — Medium
    [2, "Who wrote 'Pride and Prejudice'?", "Jane Austen", "Charlotte Brontë", "Emily Brontë", "Mary Shelley"],
    [2, "Who wrote '1984'?", "George Orwell", "Aldous Huxley", "Ray Bradbury", "H.G. Wells"],
    [2, "Who wrote 'The Hobbit'?", "J.R.R. Tolkien", "C.S. Lewis", "George R.R. Martin", "Terry Pratchett"],
    [2, "In 'The Lion, the Witch and the Wardrobe', what is the name of the lion?", "Aslan", "Mufasa", "Simba", "Leo"],
    [2, "Who wrote 'The Adventures of Tom Sawyer'?", "Mark Twain", "Jack London", "Herman Melville", "Edgar Allan Poe"],
    [2, "What is the name of the whale in 'Moby-Dick'?", "Moby Dick", "Willy", "Monstro", "Leviathan"],
    [2, "Who wrote 'Frankenstein'?", "Mary Shelley", "Bram Stoker", "Edgar Allan Poe", "Robert Louis Stevenson"],
    [2, "In 'The Hunger Games', who is Katniss's fellow tribute from District 12?", "Peeta Mellark", "Gale Hawthorne", "Cato", "Finnick Odair"],
    [2, "Who wrote 'A Christmas Carol'?", "Charles Dickens", "Lewis Carroll", "Oscar Wilde", "Thomas Hardy"],
    [2, "What is the name of the miser in 'A Christmas Carol'?", "Ebenezer Scrooge", "Jacob Marley", "Bob Cratchit", "Tiny Tim"],
    [2, "Who wrote 'Dracula'?", "Bram Stoker", "Mary Shelley", "H.P. Lovecraft", "Stephen King"],
    [2, "Who is the author of the 'Percy Jackson' series?", "Rick Riordan", "J.K. Rowling", "Suzanne Collins", "Christopher Paolini"],
    [2, "Which poet wrote 'The Raven'?", "Edgar Allan Poe", "Robert Frost", "Walt Whitman", "Emily Dickinson"],
    [2, "In 'The Great Gatsby', what is Gatsby's first name?", "Jay", "Tom", "Nick", "George"],
    [2, "Which novel begins 'Call me Ishmael'?", "Moby-Dick", "Treasure Island", "Robinson Crusoe", "The Old Man and the Sea"],
    [2, "Who wrote 'Matilda' and 'Charlie and the Chocolate Factory'?", "Roald Dahl", "Beverly Cleary", "Judy Blume", "E.B. White"],
    [2, "In 'Harry Potter', what house is Harry sorted into?", "Gryffindor", "Slytherin", "Ravenclaw", "Hufflepuff"],
    [2, "Who wrote 'The Odyssey'?", "Homer", "Virgil", "Sophocles", "Plato"],
    [2, "Who wrote 'To Kill a Mockingbird'?", "Harper Lee", "Truman Capote", "John Steinbeck", "Toni Morrison"],
    [2, "In which Shakespeare play does a character say 'Et tu, Brute?'", "Julius Caesar", "Hamlet", "Macbeth", "King Lear"],

    // Level 3 — Hard
    [3, "Who wrote 'One Hundred Years of Solitude'?", "Gabriel García Márquez", "Isabel Allende", "Jorge Luis Borges", "Mario Vargas Llosa"],
    [3, "Who wrote 'The Catcher in the Rye'?", "J.D. Salinger", "Jack Kerouac", "Ernest Hemingway", "John Steinbeck"],
    [3, "In 'Of Mice and Men', what are the names of the two main characters?", "George and Lennie", "Tom and Huck", "Jem and Scout", "Sal and Dean"],
    [3, "Who wrote 'Brave New World'?", "Aldous Huxley", "George Orwell", "Ray Bradbury", "Kurt Vonnegut"],
    [3, "In 'Fahrenheit 451', what is burned?", "Books", "Money", "Houses", "Flags"],
    [3, "Who wrote 'Jane Eyre'?", "Charlotte Brontë", "Emily Brontë", "Anne Brontë", "Jane Austen"],
    [3, "Who wrote 'War and Peace'?", "Leo Tolstoy", "Fyodor Dostoevsky", "Anton Chekhov", "Ivan Turgenev"],
    [3, "What is the name of the hobbit who carries the One Ring to Mordor?", "Frodo Baggins", "Bilbo Baggins", "Samwise Gamgee", "Meriadoc Brandybuck"],
    [3, "Which Shakespeare play features the characters Oberon and Titania?", "A Midsummer Night's Dream", "The Tempest", "Twelfth Night", "As You Like It"],
    [3, "Who wrote 'The Old Man and the Sea'?", "Ernest Hemingway", "William Faulkner", "John Steinbeck", "F. Scott Fitzgerald"],
    [3, "In George Orwell's '1984', what is the name of the all-seeing leader?", "Big Brother", "The Director", "Number One", "The Party Chair"],
    [3, "Who wrote 'Wuthering Heights'?", "Emily Brontë", "Charlotte Brontë", "Mary Shelley", "George Eliot"],
    [3, "Which novel features the characters Holden Caulfield and Phoebe?", "The Catcher in the Rye", "A Separate Peace", "On the Road", "The Outsiders"],
    [3, "Who wrote the 'A Song of Ice and Fire' series?", "George R.R. Martin", "Robert Jordan", "Brandon Sanderson", "Patrick Rothfuss"],
    [3, "In 'Animal Farm', which animals take control of the farm?", "Pigs", "Horses", "Dogs", "Sheep"],
    [3, "Who wrote 'Crime and Punishment'?", "Fyodor Dostoevsky", "Leo Tolstoy", "Nikolai Gogol", "Alexander Pushkin"],
    [3, "Which epic poem tells of the hero Beowulf fighting Grendel?", "Beowulf", "The Iliad", "The Aeneid", "Paradise Lost"],
    [3, "Who wrote 'The Divine Comedy'?", "Dante Alighieri", "Giovanni Boccaccio", "Petrarch", "Niccolò Machiavelli"],
    [3, "What is the first book of the 'Lord of the Rings' trilogy?", "The Fellowship of the Ring", "The Two Towers", "The Return of the King", "The Hobbit"],
    [3, "Who wrote 'Little Women'?", "Louisa May Alcott", "Harriet Beecher Stowe", "Edith Wharton", "Willa Cather"],

    // Level 4 — Expert
    [4, "Who wrote 'Ulysses' (1922)?", "James Joyce", "Virginia Woolf", "Samuel Beckett", "T.S. Eliot"],
    [4, "What is the name of the narrator in 'Moby-Dick'?", "Ishmael", "Ahab", "Queequeg", "Starbuck"],
    [4, "Who wrote 'Don Quixote'?", "Miguel de Cervantes", "Lope de Vega", "Federico García Lorca", "Jorge Luis Borges"],
    [4, "Which Russian author wrote 'Anna Karenina'?", "Leo Tolstoy", "Fyodor Dostoevsky", "Vladimir Nabokov", "Boris Pasternak"],
    [4, "In 'The Great Gatsby', what color is the light at the end of Daisy's dock?", "Green", "Red", "White", "Blue"],
    [4, "Who wrote 'The Canterbury Tales'?", "Geoffrey Chaucer", "John Milton", "Edmund Spenser", "William Langland"],
    [4, "Who wrote the epic poem 'Paradise Lost'?", "John Milton", "William Blake", "John Donne", "Alexander Pope"],
    [4, "Which author created the fictional county of Yoknapatawpha?", "William Faulkner", "Mark Twain", "Flannery O'Connor", "Cormac McCarthy"],
    [4, "What is the real name of the author known as George Eliot?", "Mary Ann Evans", "Charlotte Brontë", "Mary Shelley", "Elizabeth Gaskell"],
    [4, "What is the name of Don Quixote's loyal squire?", "Sancho Panza", "Dulcinea", "Rocinante", "Lazarillo"],
    [4, "Who wrote 'Things Fall Apart'?", "Chinua Achebe", "Wole Soyinka", "Ngũgĩ wa Thiong'o", "Chimamanda Ngozi Adichie"],
    [4, "Which novel is set in the dystopian Republic of Gilead?", "The Handmaid's Tale", "Never Let Me Go", "The Road", "Station Eleven"],
    [4, "Who wrote 'The Metamorphosis', where Gregor Samsa turns into an insect?", "Franz Kafka", "Albert Camus", "Thomas Mann", "Hermann Hesse"],
    [4, "What was the pen name of Samuel Clemens?", "Mark Twain", "O. Henry", "Lewis Carroll", "Saki"],
    [4, "What is the name of the ship in 'Moby-Dick'?", "Pequod", "Nautilus", "Hispaniola", "Black Pearl"],
    [4, "Who wrote 'In Search of Lost Time'?", "Marcel Proust", "Gustave Flaubert", "Victor Hugo", "Émile Zola"],
    [4, "Which poet wrote 'The Waste Land' (1922)?", "T.S. Eliot", "Ezra Pound", "W.B. Yeats", "W.H. Auden"],
    [4, "In Dante's 'Inferno', how many circles of Hell are there?", "9", "7", "10", "12"],
    [4, "Who wrote 'Les Misérables'?", "Victor Hugo", "Alexandre Dumas", "Honoré de Balzac", "Jules Verne"],
    [4, "In 'Lord of the Flies', which boy is elected leader and blows the conch?", "Ralph", "Jack", "Piggy", "Simon"],
  ],
};
