'use strict';

module.exports = {
  category: "Movies & TV",
  questions: [
    // Level 1 — Easy
    [1, "Which wizard has a lightning-bolt scar?", "Harry Potter", "Gandalf", "Merlin", "Doctor Strange"],
    [1, "What is the name of the toy cowboy in Toy Story?", "Woody", "Buzz", "Jessie", "Rex"],
    [1, "Which superhero is known as the Dark Knight?", "Batman", "Superman", "Iron Man", "Daredevil"],
    [1, "In 'Frozen', what is the name of the snowman?", "Olaf", "Sven", "Kristoff", "Hans"],
    [1, "Which TV show features the Upside Down?", "Stranger Things", "Dark", "Lost", "The Walking Dead"],
    [1, "What color is Shrek?", "Green", "Blue", "Brown", "Purple"],
    [1, "Which superhero is Peter Parker?", "Spider-Man", "Batman", "The Flash", "Ant-Man"],
    [1, "What kind of fish is Nemo?", "Clownfish", "Goldfish", "Angelfish", "Pufferfish"],
    [1, "Which princess has a pet tiger named Rajah?", "Jasmine", "Ariel", "Belle", "Mulan"],
    [1, "In 'The Lion King', who is Simba's father?", "Mufasa", "Scar", "Rafiki", "Zazu"],
    [1, "What is the name of the yellow family in a long-running cartoon set in Springfield?", "The Simpsons", "The Griffins", "The Belchers", "The Smiths"],
    [1, "What does E.T. want to do?", "Phone home", "Eat candy", "Ride a bike", "Go to school"],
    [1, "Which superhero carries a shield with a star on it?", "Captain America", "Thor", "Hulk", "Black Panther"],
    [1, "In 'Finding Nemo', which fish has short-term memory loss?", "Dory", "Marlin", "Gill", "Bruce"],
    [1, "Which movie features a giant shark terrorizing Amity Island?", "Jaws", "The Meg", "Deep Blue Sea", "Sharknado"],
    [1, "What is the name of Mickey Mouse's girlfriend?", "Minnie", "Daisy", "Clarabelle", "Pauline"],
    [1, "Which green Muppet is famous for saying 'It's not easy being green'?", "Kermit the Frog", "Oscar the Grouch", "Cookie Monster", "Gonzo"],
    [1, "Which sport is played in the 'Space Jam' movies?", "Basketball", "Soccer", "Baseball", "Football"],
    [1, "Who lives in a pineapple under the sea?", "SpongeBob SquarePants", "Patrick Star", "Squidward", "Mr. Krabs"],
    [1, "What color pill does Neo take in The Matrix?", "Red", "Blue", "Green", "White"],

    // Level 2 — Medium
    [2, "What fictional country is Black Panther from?", "Wakanda", "Genovia", "Latveria", "Sokovia"],
    [2, "Which streaming show is about a deadly children's game competition in Korea?", "Squid Game", "Alice in Borderland", "Kingdom", "All of Us Are Dead"],
    [2, "Who directed 'Jurassic Park'?", "Steven Spielberg", "James Cameron", "George Lucas", "Ridley Scott"],
    [2, "What is the name of the coffee shop in 'Friends'?", "Central Perk", "Java Joe's", "The Grind", "Monk's Café"],
    [2, "In 'Star Wars', what is Darth Vader's real name?", "Anakin Skywalker", "Luke Skywalker", "Obi-Wan Kenobi", "Ben Solo"],
    [2, "What is the highest-grossing film of all time, not adjusted for inflation (as of 2024)?", "Avatar", "Avengers: Endgame", "Titanic", "Star Wars: The Force Awakens"],
    [2, "In 'Breaking Bad', what subject does Walter White teach?", "Chemistry", "Biology", "Physics", "Math"],
    [2, "Which actor played Jack in 'Titanic'?", "Leonardo DiCaprio", "Brad Pitt", "Matt Damon", "Johnny Depp"],
    [2, "What is the name of the hobbit played by Elijah Wood?", "Frodo Baggins", "Samwise Gamgee", "Bilbo Baggins", "Pippin Took"],
    [2, "Which TV series is set in the fictional continent of Westeros?", "Game of Thrones", "The Witcher", "Vikings", "The Wheel of Time"],
    [2, "What is the name of the paper company in the U.S. version of 'The Office'?", "Dunder Mifflin", "Wernham Hogg", "Initech", "Sabre Inc."],
    [2, "In 'The Wizard of Oz', what does the Tin Man want?", "A heart", "A brain", "Courage", "A home"],
    [2, "Which film features the quote 'I'll be back'?", "The Terminator", "RoboCop", "Predator", "Die Hard"],
    [2, "What is the name of the kingdom in 'Shrek' ruled by Lord Farquaad?", "Duloc", "Far Far Away", "Arendelle", "Corona"],
    [2, "Who plays Iron Man in the Marvel Cinematic Universe?", "Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Mark Ruffalo"],
    [2, "In 'The Hunger Games', what district is Katniss from?", "District 12", "District 1", "District 7", "District 13"],
    [2, "What type of animal is Pumbaa in 'The Lion King'?", "Warthog", "Meerkat", "Hyena", "Boar"],
    [2, "Which animated film features a rat who becomes a chef in Paris?", "Ratatouille", "Flushed Away", "The Rescuers", "An American Tail"],
    [2, "What is the name of the fictional town in 'Stranger Things'?", "Hawkins", "Derry", "Riverdale", "Twin Peaks"],
    [2, "Which sitcom features the character Sheldon Cooper?", "The Big Bang Theory", "Friends", "How I Met Your Mother", "Silicon Valley"],

    // Level 3 — Hard
    [3, "Which film won the first Academy Award for Best Picture?", "Wings", "Sunrise", "The Jazz Singer", "Metropolis"],
    [3, "Who directed 'Pulp Fiction'?", "Quentin Tarantino", "Martin Scorsese", "Guy Ritchie", "David Fincher"],
    [3, "What is the name of the hotel in 'The Shining'?", "The Overlook Hotel", "The Bates Motel", "The Grand Budapest", "The Stanley"],
    [3, "Which film was the first feature-length fully computer-animated movie?", "Toy Story", "A Bug's Life", "Shrek", "Antz"],
    [3, "In 'Back to the Future', what speed must the DeLorean reach to time travel?", "88 mph", "100 mph", "77 mph", "121 mph"],
    [3, "Which South Korean film won the Academy Award for Best Picture in 2020?", "Parasite", "Oldboy", "The Handmaiden", "Burning"],
    [3, "What is the name of Walter White's alias in 'Breaking Bad'?", "Heisenberg", "Schrödinger", "Einstein", "Oppenheimer"],
    [3, "Which actor voiced the dragon Smaug in 'The Hobbit' films?", "Benedict Cumberbatch", "Martin Freeman", "Ian McKellen", "Andy Serkis"],
    [3, "Who composed the music for 'Star Wars'?", "John Williams", "Hans Zimmer", "Danny Elfman", "Howard Shore"],
    [3, "What is the name of the spaceship in 'Alien' (1979)?", "Nostromo", "Sulaco", "Event Horizon", "Prometheus"],
    [3, "Which TV show features the Dragon Queen Daenerys Targaryen?", "Game of Thrones", "House of the Dragon", "The Witcher", "Merlin"],
    [3, "In 'Inception', what object does Cobb use as his totem?", "A spinning top", "A chess piece", "A die", "A coin"],
    [3, "Who played the Joker in 'The Dark Knight' (2008)?", "Heath Ledger", "Jack Nicholson", "Joaquin Phoenix", "Jared Leto"],
    [3, "What is the name of the main character in 'The Legend of Korra'?", "Korra", "Aang", "Asami", "Katara"],
    [3, "Which film is famous for the line 'Here's looking at you, kid'?", "Casablanca", "Gone with the Wind", "Citizen Kane", "The Maltese Falcon"],
    [3, "In 'Friends', what is the name of Ross's pet monkey?", "Marcel", "Bubbles", "George", "Abu"],
    [3, "Which studio created 'Spirited Away'?", "Studio Ghibli", "Toei Animation", "Madhouse", "Kyoto Animation"],
    [3, "What is the fictional sport played on broomsticks in Harry Potter?", "Quidditch", "Gobstones", "Wizard chess", "Bludgerball"],
    [3, "Which series follows a high school chemistry teacher turned drug manufacturer?", "Breaking Bad", "Ozark", "Weeds", "Narcos"],
    [3, "In 'The Matrix', what is the name of the ship captained by Morpheus?", "Nebuchadnezzar", "Logos", "Hammer", "Osiris"],

    // Level 4 — Expert
    [4, "Which film holds the record for the most Academy Awards won (tied at 11)?", "Ben-Hur, Titanic and The Return of the King", "Gone with the Wind", "West Side Story", "Schindler's List"],
    [4, "What was the first film in the Marvel Cinematic Universe?", "Iron Man", "The Incredible Hulk", "Captain America: The First Avenger", "Thor"],
    [4, "Who directed '2001: A Space Odyssey'?", "Stanley Kubrick", "Ridley Scott", "Andrei Tarkovsky", "Steven Spielberg"],
    [4, "What is the name of the fictional newspaper where Clark Kent works?", "The Daily Planet", "The Daily Bugle", "Gotham Gazette", "The Daily Prophet"],
    [4, "In 'Citizen Kane', what is 'Rosebud'?", "A sled", "A horse", "A woman", "A house"],
    [4, "Which director made 'Seven Samurai'?", "Akira Kurosawa", "Hayao Miyazaki", "Yasujirō Ozu", "Takeshi Kitano"],
    [4, "Which TV show had an episode titled 'Ozymandias', often rated among the best ever?", "Breaking Bad", "The Sopranos", "Mad Men", "The Wire"],
    [4, "What is the name of the AI computer in '2001: A Space Odyssey'?", "HAL 9000", "Skynet", "MU-TH-UR", "Jarvis"],
    [4, "Which actress has won the most Academy Awards for acting?", "Katharine Hepburn", "Meryl Streep", "Ingrid Bergman", "Frances McDormand"],
    [4, "Which Alfred Hitchcock film features a famous shower scene?", "Psycho", "Vertigo", "The Birds", "Rear Window"],
    [4, "What is the name of the fictional company in 'Alien' that owns the ship?", "Weyland-Yutani", "Tyrell Corporation", "Cyberdyne Systems", "Umbrella Corporation"],
    [4, "In 'The Sopranos', what is the name of Tony's strip club?", "Bada Bing!", "The Bing Bang", "Satriale's", "Vesuvio"],
    [4, "Which 1927 film was the first feature-length 'talkie' with synchronized dialogue?", "The Jazz Singer", "Wings", "Metropolis", "Sunrise"],
    [4, "What is the name of the planet where 'Dune' is set?", "Arrakis", "Caladan", "Giedi Prime", "Tatooine"],
    [4, "Who directed the 'Lord of the Rings' film trilogy?", "Peter Jackson", "Guillermo del Toro", "Sam Raimi", "Christopher Nolan"],
    [4, "What is the name of Tony Stark's AI assistant before F.R.I.D.A.Y.?", "J.A.R.V.I.S.", "E.D.I.T.H.", "K.A.R.E.N.", "U.L.T.R.O.N."],
    [4, "Which film features a character named Tyler Durden?", "Fight Club", "American Psycho", "Se7en", "Trainspotting"],
    [4, "In 'Star Wars', who shot first in the Mos Eisley cantina (original 1977 release)?", "Han Solo", "Greedo", "Chewbacca", "Obi-Wan Kenobi"],
    [4, "Which TV series is set at the Baltimore docks in its second season?", "The Wire", "Homicide: Life on the Street", "Boardwalk Empire", "The Shield"],
    [4, "Which composer scored 'Inception' and 'Interstellar'?", "Hans Zimmer", "John Williams", "Ennio Morricone", "Ludwig Göransson"],
  ],
};
