'use strict';

module.exports = {
  category: "Music",
  questions: [
    // Level 1 — Easy
    [1, "Who is known as the 'King of Pop'?", "Michael Jackson", "Elvis Presley", "Prince", "Justin Timberlake"],
    [1, "Which band sang 'Bohemian Rhapsody'?", "Queen", "The Beatles", "Led Zeppelin", "ABBA"],
    [1, "How many strings does a standard violin have?", "4", "5", "6", "3"],
    [1, "Who is known as the 'King of Rock and Roll'?", "Elvis Presley", "Chuck Berry", "Little Richard", "Johnny Cash"],
    [1, "Which instrument is a small wind instrument often learned in elementary school?", "Recorder", "Drum", "Piano", "Triangle"],
    [1, "Which band was made up of John, Paul, George and Ringo?", "The Beatles", "The Rolling Stones", "The Who", "The Kinks"],
    [1, "Which instrument do you hit with sticks?", "Drums", "Trumpet", "Violin", "Clarinet"],
    [1, "What is a group of four musicians called?", "Quartet", "Trio", "Quintet", "Duet"],
    [1, "Which singer is famous for the album '1989' and 'Shake It Off'?", "Taylor Swift", "Katy Perry", "Ariana Grande", "Selena Gomez"],
    [1, "Which instrument is a brass instrument?", "Trumpet", "Flute", "Violin", "Harp"],
    [1, "Which Swedish group sang 'Dancing Queen'?", "ABBA", "Roxette", "Ace of Base", "Europe"],
    [1, "What do you call the person who leads an orchestra?", "Conductor", "Composer", "Soloist", "Drummer"],
    [1, "Which singer is known as 'Queen B' and sang 'Single Ladies'?", "Beyoncé", "Rihanna", "Shakira", "Lady Gaga"],
    [1, "Which music genre is Johnny Cash most associated with?", "Country", "Hip-hop", "Jazz", "Metal"],
    [1, "How many lines are in a musical staff?", "5", "4", "6", "7"],
    [1, "Which rapper's real name is Marshall Mathers?", "Eminem", "Drake", "Jay-Z", "Kanye West"],
    [1, "Which instrument has a bow and is held under the chin?", "Violin", "Cello", "Guitar", "Banjo"],
    [1, "Which singer had a hit with 'Hello' (2015) and 'Rolling in the Deep'?", "Adele", "Sia", "Dua Lipa", "Lorde"],
    [1, "Which band had a hit with 'Smells Like Teen Spirit'?", "Nirvana", "Pearl Jam", "Soundgarden", "Foo Fighters"],
    [1, "Which K-pop group has members named RM, Jin, Suga, J-Hope, Jimin, V and Jungkook?", "BTS", "EXO", "Seventeen", "Stray Kids"],

    // Level 2 — Medium
    [2, "Who composed the 'Moonlight Sonata'?", "Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Johann Sebastian Bach", "Frédéric Chopin"],
    [2, "Which artist released the album 'Thriller'?", "Michael Jackson", "Prince", "Madonna", "Whitney Houston"],
    [2, "Which country is the band U2 from?", "Ireland", "Scotland", "England", "Wales"],
    [2, "Which singer is known as the 'Queen of Pop'?", "Madonna", "Britney Spears", "Lady Gaga", "Cher"],
    [2, "What is the highest female singing voice?", "Soprano", "Alto", "Mezzo-soprano", "Tenor"],
    [2, "Which rapper released the album 'To Pimp a Butterfly'?", "Kendrick Lamar", "J. Cole", "Drake", "Kanye West"],
    [2, "Which instrument did Jimi Hendrix famously play?", "Electric guitar", "Bass guitar", "Drums", "Saxophone"],
    [2, "Which British band sang 'Wonderwall'?", "Oasis", "Blur", "Radiohead", "Coldplay"],
    [2, "Which Canadian singer was discovered on YouTube and sang 'Baby'?", "Justin Bieber", "Shawn Mendes", "The Weeknd", "Drake"],
    [2, "Who sang 'Purple Rain'?", "Prince", "Michael Jackson", "David Bowie", "Stevie Wonder"],
    [2, "Which band sang 'Don't Stop Believin''?", "Journey", "Boston", "Foreigner", "Toto"],
    [2, "Which band released 'Hotel California'?", "Eagles", "Fleetwood Mac", "The Doors", "Journey"],
    [2, "Which singer's fans are called 'Little Monsters'?", "Lady Gaga", "Katy Perry", "Nicki Minaj", "Billie Eilish"],
    [2, "What Italian term means to play loudly?", "Forte", "Piano", "Allegro", "Largo"],
    [2, "Which artist sang 'Blinding Lights'?", "The Weeknd", "Bruno Mars", "Harry Styles", "Post Malone"],
    [2, "Which composer wrote 'The Four Seasons'?", "Antonio Vivaldi", "Johann Sebastian Bach", "George Frideric Handel", "Joseph Haydn"],
    [2, "Which band is Freddie Mercury famous for fronting?", "Queen", "Aerosmith", "Def Leppard", "Kiss"],
    [2, "Which singer released 'Bad Guy' as a teenager?", "Billie Eilish", "Olivia Rodrigo", "Lorde", "Halsey"],
    [2, "Reggae music originated in which country?", "Jamaica", "Trinidad and Tobago", "Cuba", "Barbados"],
    [2, "Which instrument has pedals, pipes and is often found in churches?", "Organ", "Harpsichord", "Accordion", "Piano"],

    // Level 3 — Hard
    [3, "What was the name of Elvis Presley's home in Memphis?", "Graceland", "Neverland", "Paisley Park", "Sun Studio"],
    [3, "Which composer continued to compose after becoming almost completely deaf?", "Ludwig van Beethoven", "Johann Sebastian Bach", "Franz Schubert", "Richard Wagner"],
    [3, "Which band's best-selling album is 'The Dark Side of the Moon'?", "Pink Floyd", "Led Zeppelin", "The Who", "Genesis"],
    [3, "Which jazz musician was nicknamed 'Satchmo'?", "Louis Armstrong", "Miles Davis", "Duke Ellington", "Dizzy Gillespie"],
    [3, "What is the name of Beyoncé's 2016 visual album?", "Lemonade", "Renaissance", "4", "Dangerously in Love"],
    [3, "Which rapper founded Roc-A-Fella Records with Damon Dash and Kareem Burke?", "Jay-Z", "Kanye West", "Nas", "Dr. Dre"],
    [3, "How many symphonies did Beethoven complete?", "9", "5", "7", "12"],
    [3, "Which singer is nicknamed 'The Boss'?", "Bruce Springsteen", "Bob Dylan", "Billy Joel", "Tom Petty"],
    [3, "What is the term for a piece of music written for a solo instrument with orchestra?", "Concerto", "Symphony", "Sonata", "Overture"],
    [3, "Which country did the tango originate in, along the Río de la Plata?", "Argentina and Uruguay", "Spain", "Brazil", "Cuba"],
    [3, "Which band sang 'Stairway to Heaven'?", "Led Zeppelin", "Deep Purple", "Black Sabbath", "The Doors"],
    [3, "Which opera composer wrote 'The Magic Flute'?", "Mozart", "Verdi", "Puccini", "Wagner"],
    [3, "Which artist won Album of the Year at the Grammys for '21'?", "Adele", "Taylor Swift", "Bruno Mars", "Beyoncé"],
    [3, "Which rapper was born Calvin Broadus?", "Snoop Dogg", "Ice Cube", "Dr. Dre", "50 Cent"],
    [3, "What does 'a cappella' mean?", "Singing without instruments", "Singing very fast", "Singing in Italian", "Singing in a church only"],
    [3, "Which guitarist is known as 'Slowhand'?", "Eric Clapton", "Jimmy Page", "Keith Richards", "Jeff Beck"],
    [3, "Which band's members wore makeup and were nicknamed 'The Demon' and 'Starchild'?", "Kiss", "Mötley Crüe", "Alice Cooper", "Twisted Sister"],
    [3, "Which city is considered the birthplace of jazz?", "New Orleans", "Chicago", "New York", "Memphis"],
    [3, "Which singer released the album 'Back to Black'?", "Amy Winehouse", "Adele", "Duffy", "Lily Allen"],
    [3, "What is the lowest standard adult male singing voice?", "Bass", "Baritone", "Tenor", "Alto"],

    // Level 4 — Expert
    [4, "Which composer wrote the opera 'The Ring of the Nibelung'?", "Richard Wagner", "Giuseppe Verdi", "Richard Strauss", "Gustav Mahler"],
    [4, "What is the name of the record label founded by Berry Gordy in Detroit?", "Motown", "Stax", "Atlantic", "Chess"],
    [4, "Which classical composer was a child prodigy who toured Europe at age six?", "Wolfgang Amadeus Mozart", "Ludwig van Beethoven", "Franz Liszt", "Johannes Brahms"],
    [4, "Which album by The Beatles features the song 'A Day in the Life'?", "Sgt. Pepper's Lonely Hearts Club Band", "Abbey Road", "Revolver", "The White Album"],
    [4, "Which musician was known as 'The Godfather of Soul'?", "James Brown", "Ray Charles", "Marvin Gaye", "Otis Redding"],
    [4, "Which country singer wrote and first recorded 'I Will Always Love You'?", "Dolly Parton", "Whitney Houston", "Patsy Cline", "Loretta Lynn"],
    [4, "Which artist released the album 'OK Computer' in 1997?", "Radiohead", "Blur", "Muse", "Portishead"],
    [4, "What is the time signature of a waltz?", "3/4", "4/4", "2/4", "6/8"],
    [4, "Which composer wrote 'Clair de lune'?", "Claude Debussy", "Maurice Ravel", "Erik Satie", "Gabriel Fauré"],
    [4, "Which rapper's debut studio album was 'Illmatic' (1994)?", "Nas", "The Notorious B.I.G.", "Jay-Z", "Tupac Shakur"],
    [4, "Which instrument is Yo-Yo Ma famous for playing?", "Cello", "Violin", "Piano", "Viola"],
    [4, "What does 'BPM' stand for in music?", "Beats per minute", "Bars per measure", "Bass per mix", "Beats per measure"],
    [4, "Which festival took place in August 1969 in Bethel, New York?", "Woodstock", "Monterey Pop", "Altamont", "Isle of Wight"],
    [4, "Who composed 'The Rite of Spring', which caused a riot at its 1913 premiere?", "Igor Stravinsky", "Sergei Prokofiev", "Dmitri Shostakovich", "Pyotr Tchaikovsky"],
    [4, "Which band released the album 'Rumours' in 1977?", "Fleetwood Mac", "Eagles", "The Rolling Stones", "Steely Dan"],
    [4, "Which singer was known as the 'Queen of Soul'?", "Aretha Franklin", "Diana Ross", "Etta James", "Tina Turner"],
    [4, "Which Baroque composer wrote the 'Brandenburg Concertos'?", "Johann Sebastian Bach", "Antonio Vivaldi", "George Frideric Handel", "Henry Purcell"],
    [4, "What is the name of David Bowie's alien rock-star persona?", "Ziggy Stardust", "Major Tom", "The Thin White Duke", "Aladdin Sane"],
    [4, "In music notation, what does a sharp (♯) do to a note?", "Raises it by a half step", "Lowers it by a half step", "Makes it louder", "Holds it longer"],
    [4, "Which ballet by Tchaikovsky features the Sugar Plum Fairy?", "The Nutcracker", "Swan Lake", "Sleeping Beauty", "Giselle"],
  ],
};
