'use strict';

module.exports = {
  category: "Mythology",
  questions: [
    // Level 1 — Easy
    [1, "Who is the king of the Greek gods?", "Zeus", "Poseidon", "Hades", "Apollo"],
    [1, "Which Norse god wields a hammer named Mjölnir?", "Thor", "Odin", "Loki", "Freyr"],
    [1, "What creature is half man and half horse?", "Centaur", "Minotaur", "Satyr", "Sphinx"],
    [1, "Which Greek god rules the sea?", "Poseidon", "Zeus", "Ares", "Hermes"],
    [1, "What mythical creature is a horse with a single horn?", "Unicorn", "Pegasus", "Griffin", "Hippogriff"],
    [1, "What is the name of the winged horse in Greek myth?", "Pegasus", "Bucephalus", "Sleipnir", "Arion"],
    [1, "Which Greek god rules the underworld?", "Hades", "Ares", "Hermes", "Dionysus"],
    [1, "Which Norse trickster god is Thor's adopted brother?", "Loki", "Baldur", "Heimdall", "Tyr"],
    [1, "Which mythical bird rises from its own ashes?", "Phoenix", "Roc", "Thunderbird", "Harpy"],
    [1, "What sea creature is half woman and half fish?", "Mermaid", "Siren (bird form)", "Selkie", "Kraken"],
    [1, "In Greek myth, which hero was super strong and did twelve labors?", "Heracles (Hercules)", "Achilles", "Perseus", "Odysseus"],
    [1, "Which Roman god of love shoots arrows to make people fall in love?", "Cupid", "Mars", "Neptune", "Apollo"],
    [1, "Which monster had snakes for hair and turned people to stone?", "Medusa", "Hydra", "Chimera", "Cyclops"],
    [1, "What one-eyed giant did Odysseus blind?", "A Cyclops (Polyphemus)", "A Titan", "A Minotaur", "A Giant snake"],
    [1, "Which fire-breathing creature often guards treasure in legends?", "Dragon", "Unicorn", "Gnome", "Fairy"],
    [1, "Mount Olympus is the home of which gods?", "Greek gods", "Norse gods", "Egyptian gods", "Hindu gods"],
    [1, "Which Greek goddess is associated with wisdom and owls?", "Athena", "Aphrodite", "Hera", "Artemis"],
    [1, "Which Greek goddess is associated with love and beauty?", "Aphrodite", "Athena", "Demeter", "Hestia"],
    [1, "Which legendary British king pulled a sword from a stone?", "King Arthur", "Richard the Lionheart", "King Alfred", "King Lear"],
    [1, "What is the name of King Arthur's sword?", "Excalibur", "Durendal", "Gram", "Andúril"],

    // Level 2 — Medium
    [2, "Who is the chief god in Norse mythology?", "Odin", "Thor", "Freyr", "Tyr"],
    [2, "What is the Roman name for the Greek god Zeus?", "Jupiter", "Mars", "Saturn", "Neptune"],
    [2, "What is the Roman name for Ares, god of war?", "Mars", "Mercury", "Vulcan", "Pluto"],
    [2, "Which Egyptian god has the head of a jackal?", "Anubis", "Horus", "Ra", "Thoth"],
    [2, "Which Egyptian god is the sun god?", "Ra", "Osiris", "Set", "Anubis"],
    [2, "What is the name of the Norse realm of the gods?", "Asgard", "Midgard", "Jotunheim", "Helheim"],
    [2, "Which Greek hero killed Medusa?", "Perseus", "Theseus", "Jason", "Heracles"],
    [2, "Which Greek hero killed the Minotaur?", "Theseus", "Perseus", "Achilles", "Odysseus"],
    [2, "What was Achilles' only weak spot?", "His heel", "His shoulder", "His eye", "His back"],
    [2, "What is the name of the hall where Norse warriors go after death?", "Valhalla", "Elysium", "Hel", "Folkvangr"],
    [2, "Who opened a jar (often called a box) releasing evils into the world?", "Pandora", "Persephone", "Psyche", "Penelope"],
    [2, "Which Greek messenger god wears winged sandals?", "Hermes", "Apollo", "Ares", "Hephaestus"],
    [2, "What multi-headed serpent grows two heads for each one cut off?", "Hydra", "Cerberus", "Chimera", "Scylla"],
    [2, "What is the name of the three-headed dog that guards the underworld?", "Cerberus", "Orthrus", "Fenrir", "Garmr"],
    [2, "Who flew too close to the sun on wings of wax and feathers?", "Icarus", "Daedalus", "Phaethon", "Bellerophon"],
    [2, "Which Greek goddess is the wife of Zeus and queen of the gods?", "Hera", "Athena", "Demeter", "Rhea"],
    [2, "What is the Norse world tree called?", "Yggdrasil", "Bifröst", "Gjallarhorn", "Mímir"],
    [2, "Which Greek god is associated with wine and festivity?", "Dionysus", "Apollo", "Hermes", "Hephaestus"],
    [2, "In Greek myth, who is the god of the forge and blacksmiths?", "Hephaestus", "Ares", "Hermes", "Apollo"],
    [2, "Which Egyptian god of the dead was killed by his brother Set?", "Osiris", "Ra", "Anubis", "Horus"],

    // Level 3 — Hard
    [3, "What is the name of Odin's eight-legged horse?", "Sleipnir", "Pegasus", "Hrímfaxi", "Gullfaxi"],
    [3, "What is the rainbow bridge connecting Asgard and Midgard?", "Bifröst", "Gjallarbrú", "Yggdrasil", "Vigrid"],
    [3, "Which Titan stole fire from the gods and gave it to humans?", "Prometheus", "Atlas", "Kronos", "Epimetheus"],
    [3, "Which Titan was forced to hold up the sky?", "Atlas", "Prometheus", "Hyperion", "Oceanus"],
    [3, "What is the name of the Norse end-of-the-world battle?", "Ragnarök", "Fimbulwinter", "Gjallarhorn", "Valkyrja"],
    [3, "In Hindu mythology, which god has the head of an elephant?", "Ganesha", "Shiva", "Vishnu", "Hanuman"],
    [3, "Which Greek goddess of the harvest is the mother of Persephone?", "Demeter", "Hera", "Hestia", "Artemis"],
    [3, "What was the name of Jason's ship on the quest for the Golden Fleece?", "Argo", "Odyssey", "Pequod", "Nautilus"],
    [3, "Which monster in Greek myth was half man, half bull?", "Minotaur", "Centaur", "Satyr", "Chimera"],
    [3, "Which Greek god is associated with the sun, music and prophecy?", "Apollo", "Helios", "Hermes", "Dionysus"],
    [3, "Who is the Norse god who guards the Bifröst?", "Heimdall", "Tyr", "Baldur", "Vidar"],
    [3, "In Egyptian myth, what bird-headed god is associated with writing and wisdom?", "Thoth", "Horus", "Ra", "Khonsu"],
    [3, "What is the name of the giant wolf destined to kill Odin at Ragnarök?", "Fenrir", "Sköll", "Hati", "Garmr"],
    [3, "Which Greek hero's journey home from Troy took ten years?", "Odysseus", "Achilles", "Ajax", "Menelaus"],
    [3, "What did King Midas turn everything he touched into?", "Gold", "Stone", "Ice", "Silver"],
    [3, "Which Roman god has two faces looking in opposite directions?", "Janus", "Saturn", "Mercury", "Vulcan"],
    [3, "Who was the Greek goddess of the hunt?", "Artemis", "Athena", "Hestia", "Nike"],
    [3, "Which Hindu god is known as the Destroyer in the Trimurti?", "Shiva", "Brahma", "Vishnu", "Indra"],
    [3, "What creatures lured sailors with enchanting songs?", "Sirens", "Harpies", "Nymphs", "Muses"],
    [3, "In Japanese folklore, what are the fox spirits called?", "Kitsune", "Tanuki", "Kappa", "Oni"],

    // Level 4 — Expert
    [4, "Who is the Greek primordial deity of chaos from which the universe began?", "Chaos", "Gaia", "Uranus", "Nyx"],
    [4, "Which Titan was the father of Zeus?", "Kronos", "Hyperion", "Oceanus", "Iapetus"],
    [4, "In Norse myth, what is the name of Thor's home realm?", "Thrudheim", "Vanaheim", "Alfheim", "Niflheim"],
    [4, "In Mesopotamian myth, who is the hero-king of the oldest known epic?", "Gilgamesh", "Enkidu", "Marduk", "Ashurbanipal"],
    [4, "What is the name of the Aztec feathered serpent god?", "Quetzalcoatl", "Tezcatlipoca", "Huitzilopochtli", "Tlaloc"],
    [4, "Which Norse god sacrificed his eye for wisdom at Mímir's well?", "Odin", "Tyr", "Heimdall", "Thor"],
    [4, "Which Norse god lost his hand to the wolf Fenrir?", "Tyr", "Odin", "Vidar", "Thor"],
    [4, "What is the name of the river souls cross to enter the Greek underworld?", "Styx", "Nile", "Eridanos", "Alpheus"],
    [4, "Who is the ferryman of the dead in Greek mythology?", "Charon", "Hermes", "Thanatos", "Hypnos"],
    [4, "In Egyptian myth, what is weighed against a feather in the afterlife?", "The heart", "The brain", "The soul's shadow", "The tongue"],
    [4, "Which goddess is the Egyptian deity of the feather of truth and justice?", "Ma'at", "Isis", "Hathor", "Bastet"],
    [4, "Who is the Hindu monkey god devoted to Rama?", "Hanuman", "Ganesha", "Garuda", "Krishna"],
    [4, "In Irish mythology, who is the great hero known as the Hound of Ulster?", "Cú Chulainn", "Fionn mac Cumhaill", "Oisín", "Lugh"],
    [4, "Which Greek nymph could only repeat the last words spoken to her?", "Echo", "Daphne", "Calypso", "Arethusa"],
    [4, "Who was the Greek youth who fell in love with his own reflection?", "Narcissus", "Hyacinthus", "Adonis", "Ganymede"],
    [4, "What is the Polynesian demigod who pulled islands from the sea with a fishhook?", "Māui", "Tangaroa", "Pele", "Kāne"],
    [4, "In Norse myth, what is the name of the serpent that encircles Midgard?", "Jörmungandr", "Níðhöggr", "Fáfnir", "Ratatoskr"],
    [4, "Which Greek goddess personifies victory?", "Nike", "Nemesis", "Tyche", "Eris"],
    [4, "Who was the Babylonian chief god who defeated Tiamat?", "Marduk", "Enlil", "Anu", "Ea"],
    [4, "Which Slavic witch lives in a hut standing on chicken legs?", "Baba Yaga", "Rusalka", "Kikimora", "Morana"],
  ],
};
