'use strict';

module.exports = {
  category: "Science",
  questions: [
    // Level 1 — Easy
    [1, "What planet is known as the Red Planet?", "Mars", "Venus", "Jupiter", "Mercury"],
    [1, "What gas do plants absorb from the air?", "Carbon dioxide", "Oxygen", "Nitrogen", "Helium"],
    [1, "What is H2O more commonly called?", "Water", "Salt", "Sugar", "Ozone"],
    [1, "What is the closest star to Earth?", "The Sun", "Proxima Centauri", "Sirius", "Polaris"],
    [1, "Which organ pumps blood through the body?", "Heart", "Liver", "Lungs", "Kidneys"],
    [1, "What force keeps us on the ground?", "Gravity", "Magnetism", "Friction", "Wind"],
    [1, "At what temperature does water boil at sea level (°C)?", "100", "90", "110", "212"],
    [1, "Which organ do we use to breathe?", "Lungs", "Stomach", "Heart", "Brain"],
    [1, "What is the natural satellite of Earth?", "The Moon", "The Sun", "Mars", "Venus"],
    [1, "Which part of the plant usually grows underground?", "Roots", "Leaves", "Flowers", "Fruit"],
    [1, "What do caterpillars turn into?", "Butterflies or moths", "Beetles", "Bees", "Spiders"],
    [1, "Which sense do you use your nose for?", "Smell", "Taste", "Touch", "Hearing"],
    [1, "What is the solid form of water?", "Ice", "Steam", "Vapor", "Rain"],
    [1, "Which planet do we live on?", "Earth", "Mars", "Venus", "Saturn"],
    [1, "What do we call animals that eat only plants?", "Herbivores", "Carnivores", "Omnivores", "Insectivores"],
    [1, "What tool do scientists use to look at very small things?", "Microscope", "Telescope", "Periscope", "Stethoscope"],
    [1, "What is the center of an atom called?", "Nucleus", "Electron", "Shell", "Orbit"],
    [1, "Which planet has the most famous rings?", "Saturn", "Mars", "Mercury", "Venus"],
    [1, "Rainbows appear when sunlight passes through what?", "Water droplets", "Dust", "Smoke", "Snow"],
    [1, "What do you call molten rock that comes out of a volcano?", "Lava", "Magma", "Ash", "Basalt"],

    // Level 2 — Medium
    [2, "What is the chemical symbol for gold?", "Au", "Ag", "Gd", "Go"],
    [2, "How many bones are in the adult human body?", "206", "186", "226", "256"],
    [2, "What part of the cell is called the powerhouse?", "Mitochondria", "Nucleus", "Ribosome", "Golgi body"],
    [2, "What is the chemical symbol for sodium?", "Na", "So", "Sd", "S"],
    [2, "How many planets are in our solar system?", "8", "9", "7", "10"],
    [2, "What is the largest organ of the human body?", "Skin", "Liver", "Brain", "Lungs"],
    [2, "What kind of energy does a moving object have?", "Kinetic", "Potential", "Thermal", "Nuclear"],
    [2, "What is the speed of light, approximately?", "300,000 km/s", "30,000 km/s", "3,000 km/s", "3,000,000 km/s"],
    [2, "What is the pH of pure water?", "7", "0", "14", "5"],
    [2, "Which blood cells help fight infection?", "White blood cells", "Red blood cells", "Platelets", "Plasma"],
    [2, "Which planet is the hottest in our solar system?", "Venus", "Mercury", "Mars", "Jupiter"],
    [2, "What is the process by which plants make food from sunlight?", "Photosynthesis", "Respiration", "Fermentation", "Transpiration"],
    [2, "What is the chemical formula for table salt?", "NaCl", "KCl", "NaOH", "CaCO3"],
    [2, "Which scientist proposed the theory of relativity?", "Albert Einstein", "Isaac Newton", "Niels Bohr", "Galileo Galilei"],
    [2, "What is the hardest part of the human body?", "Tooth enamel", "Femur", "Skull", "Fingernail"],
    [2, "What particle has a negative charge?", "Electron", "Proton", "Neutron", "Photon"],
    [2, "What is the main gas found in the Sun?", "Hydrogen", "Helium", "Oxygen", "Carbon"],
    [2, "How many chambers does the human heart have?", "4", "2", "3", "6"],
    [2, "What do we call a scientist who studies rocks?", "Geologist", "Biologist", "Meteorologist", "Botanist"],
    [2, "Which vitamin does sunlight help your body make?", "Vitamin D", "Vitamin C", "Vitamin A", "Vitamin K"],

    // Level 3 — Hard
    [3, "What is the atomic number of carbon?", "6", "8", "12", "14"],
    [3, "Who discovered penicillin?", "Alexander Fleming", "Louis Pasteur", "Joseph Lister", "Edward Jenner"],
    [3, "What is the chemical symbol for iron?", "Fe", "Ir", "In", "Fr"],
    [3, "What is the most common element in the universe?", "Hydrogen", "Helium", "Oxygen", "Carbon"],
    [3, "What is the unit of electrical resistance?", "Ohm", "Volt", "Ampere", "Watt"],
    [3, "Which planet has the shortest day?", "Jupiter", "Saturn", "Earth", "Mercury"],
    [3, "What type of bond shares electrons between atoms?", "Covalent", "Ionic", "Metallic", "Hydrogen"],
    [3, "What is the name of the largest moon of Saturn?", "Titan", "Europa", "Ganymede", "Enceladus"],
    [3, "DNA stands for deoxyribonucleic what?", "Acid", "Amine", "Atom", "Allele"],
    [3, "What is the smallest bone in the human body?", "Stapes", "Incus", "Malleus", "Coccyx"],
    [3, "What is absolute zero in Celsius?", "−273.15 °C", "−100 °C", "−459.67 °C", "0 °C"],
    [3, "Which gas makes up about 21% of Earth's atmosphere?", "Oxygen", "Nitrogen", "Argon", "Carbon dioxide"],
    [3, "What is the SI unit of force?", "Newton", "Joule", "Pascal", "Watt"],
    [3, "Which organ produces insulin?", "Pancreas", "Liver", "Kidney", "Gallbladder"],
    [3, "What is the name of the galaxy we live in?", "Milky Way", "Andromeda", "Triangulum", "Sombrero"],
    [3, "Which element is liquid at room temperature and is a metal?", "Mercury", "Gallium", "Lead", "Bromine"],
    [3, "How many pairs of chromosomes do humans usually have?", "23", "22", "24", "46"],
    [3, "Who developed the three laws of motion?", "Isaac Newton", "Galileo Galilei", "Johannes Kepler", "Albert Einstein"],
    [3, "What is the study of fungi called?", "Mycology", "Virology", "Botany", "Entomology"],
    [3, "What does a seismograph measure?", "Earthquakes", "Wind speed", "Rainfall", "Air pressure"],

    // Level 4 — Expert
    [4, "What is the chemical symbol for tungsten?", "W", "Tu", "Tg", "Ts"],
    [4, "What is Avogadro's number, approximately?", "6.022 × 10²³", "3.14 × 10²³", "9.81 × 10²³", "1.602 × 10²³"],
    [4, "Which subatomic particle was discovered by J.J. Thomson in 1897?", "Electron", "Proton", "Neutron", "Positron"],
    [4, "What is the hardest known naturally occurring mineral on the Mohs scale?", "Diamond", "Corundum", "Topaz", "Quartz"],
    [4, "What is the name of the boundary around a black hole beyond which nothing escapes?", "Event horizon", "Photon sphere", "Singularity", "Ergosphere"],
    [4, "Which element has the highest melting point?", "Tungsten", "Iron", "Titanium", "Platinum"],
    [4, "What is the powerhouse molecule that stores energy in cells?", "ATP", "DNA", "RNA", "NADH"],
    [4, "What is the name of the protein that carries oxygen in red blood cells?", "Hemoglobin", "Myoglobin", "Insulin", "Collagen"],
    [4, "Who is credited with creating the first widely recognized periodic table?", "Dmitri Mendeleev", "John Dalton", "Marie Curie", "Antoine Lavoisier"],
    [4, "What is the half-life of carbon-14, approximately?", "5,730 years", "1,200 years", "57,300 years", "730 years"],
    [4, "Which planet rotates on its side, with an axial tilt of about 98 degrees?", "Uranus", "Neptune", "Saturn", "Venus"],
    [4, "What phenomenon makes a passing siren change pitch?", "Doppler effect", "Refraction", "Interference", "Resonance"],
    [4, "What is the term for an organism that can make its own food?", "Autotroph", "Heterotroph", "Saprotroph", "Detritivore"],
    [4, "What is the only noble gas without a full outer shell of eight electrons?", "Helium", "Neon", "Argon", "Radon"],
    [4, "Which scientist won Nobel Prizes in both Physics and Chemistry?", "Marie Curie", "Linus Pauling", "Albert Einstein", "Niels Bohr"],
    [4, "What is the approximate age of the universe?", "13.8 billion years", "4.5 billion years", "20 billion years", "1 billion years"],
    [4, "What is the name of the layer of the atmosphere where most weather happens?", "Troposphere", "Stratosphere", "Mesosphere", "Thermosphere"],
    [4, "What does the 'c' stand for in E = mc²?", "Speed of light", "Charge", "Constant of gravity", "Calories"],
    [4, "Which part of the brain controls balance and coordination?", "Cerebellum", "Cerebrum", "Medulla", "Hypothalamus"],
    [4, "What is the name for animals with a backbone?", "Vertebrates", "Invertebrates", "Arthropods", "Mollusks"],
  ],
};
