'use strict';

module.exports = {
  category: "Sports",
  questions: [
    // Level 1 — Easy
    [1, "In which sport would you perform a slam dunk?", "Basketball", "Volleyball", "Tennis", "Handball"],
    [1, "How many rings are on the Olympic flag?", "5", "4", "6", "7"],
    [1, "What sport is played at Wimbledon?", "Tennis", "Cricket", "Golf", "Polo"],
    [1, "Which sport uses a shuttlecock?", "Badminton", "Squash", "Table tennis", "Lacrosse"],
    [1, "How many players are on the field for one soccer team?", "11", "10", "9", "12"],
    [1, "In which sport do you score a 'home run'?", "Baseball", "Cricket", "Rugby", "Hockey"],
    [1, "What color is the center of an archery target, worth the most points?", "Gold/yellow", "Red", "Blue", "Black"],
    [1, "Which sport is played on ice with a puck?", "Ice hockey", "Curling", "Figure skating", "Bobsled"],
    [1, "What is the name of the sport where you ride waves on a board?", "Surfing", "Skating", "Skiing", "Rowing"],
    [1, "How many points is a touchdown worth in American football?", "6", "3", "7", "2"],
    [1, "In golf, what is the term for one stroke under par?", "Birdie", "Eagle", "Bogey", "Albatross"],
    [1, "Which sport is Usain Bolt famous for?", "Sprinting", "Swimming", "Boxing", "Cycling"],
    [1, "In tennis, what is a score of zero called?", "Love", "Nil", "Duck", "Zip"],
    [1, "What is the shape of a rugby ball?", "Oval", "Round", "Square", "Triangular"],
    [1, "Which country is famous for sumo wrestling?", "Japan", "China", "Mongolia", "Korea"],
    [1, "How many holes are on a standard golf course?", "18", "9", "12", "21"],
    [1, "What is a perfect score in ten-pin bowling?", "300", "200", "250", "100"],
    [1, "Which sport uses a bat, a ball and wickets?", "Cricket", "Baseball", "Softball", "Rounders"],
    [1, "In which sport might you see a 'knockout'?", "Boxing", "Golf", "Swimming", "Tennis"],
    [1, "Which piece of equipment do you need to play basketball?", "A hoop", "A net on the ground", "A bat", "A puck"],

    // Level 2 — Medium
    [2, "Which country has won the most FIFA World Cups?", "Brazil", "Germany", "Italy", "Argentina"],
    [2, "How long is a marathon, approximately?", "26.2 miles", "13.1 miles", "20 miles", "30 miles"],
    [2, "Which athlete has won the most Olympic gold medals?", "Michael Phelps", "Usain Bolt", "Carl Lewis", "Larisa Latynina"],
    [2, "How many players are on a basketball team on the court?", "5", "6", "7", "4"],
    [2, "Which country hosted the 2016 Summer Olympics?", "Brazil", "China", "United Kingdom", "Japan"],
    [2, "What is the national sport of Canada (winter)?", "Ice hockey", "Lacrosse", "Curling", "Skiing"],
    [2, "Which NBA player is nicknamed 'King James'?", "LeBron James", "James Harden", "Kevin Durant", "Michael Jordan"],
    [2, "In which sport is the Stanley Cup awarded?", "Ice hockey", "Basketball", "Baseball", "American football"],
    [2, "How many points is a free throw worth in basketball?", "1", "2", "3", "0.5"],
    [2, "Which soccer player is nicknamed 'CR7'?", "Cristiano Ronaldo", "Ronaldinho", "Ronaldo Nazário", "Kylian Mbappé"],
    [2, "How long is an Olympic swimming pool?", "50 meters", "25 meters", "100 meters", "75 meters"],
    [2, "What is the term for three goals by one player in a soccer game?", "Hat-trick", "Triple", "Treble", "Turkey"],
    [2, "Which tennis tournament is played on clay courts in Paris?", "French Open", "Wimbledon", "US Open", "Australian Open"],
    [2, "In which sport is the Ryder Cup contested?", "Golf", "Tennis", "Sailing", "Cricket"],
    [2, "Who invented basketball in 1891?", "James Naismith", "Walter Camp", "Abner Doubleday", "William Morgan"],
    [2, "Which boxer was known as 'The Greatest'?", "Muhammad Ali", "Mike Tyson", "Joe Frazier", "George Foreman"],
    [2, "What is the maximum break in snooker (standard)?", "147", "155", "100", "180"],
    [2, "Which city hosted the 2012 Summer Olympics?", "London", "Beijing", "Rio de Janeiro", "Athens"],
    [2, "In American football, how many points is a field goal worth?", "3", "2", "6", "1"],
    [2, "Which sport features the Tour de France?", "Cycling", "Running", "Motor racing", "Sailing"],

    // Level 3 — Hard
    [3, "Which country won the first FIFA World Cup in 1930?", "Uruguay", "Brazil", "Argentina", "Italy"],
    [3, "In darts, what is the highest possible score with three darts?", "180", "150", "160", "200"],
    [3, "Who holds the men's 100m world record (9.58s)?", "Usain Bolt", "Tyson Gay", "Yohan Blake", "Justin Gatlin"],
    [3, "Which golfer is nicknamed 'The Golden Bear'?", "Jack Nicklaus", "Arnold Palmer", "Tiger Woods", "Gary Player"],
    [3, "How many Grand Slam tournaments are there in tennis each year?", "4", "3", "5", "6"],
    [3, "Which country won the 2014 FIFA World Cup?", "Germany", "Argentina", "Spain", "Brazil"],
    [3, "Which NBA team did Michael Jordan win six championships with?", "Chicago Bulls", "Washington Wizards", "Los Angeles Lakers", "Boston Celtics"],
    [3, "In which sport would you perform a 'Fosbury Flop'?", "High jump", "Pole vault", "Long jump", "Diving"],
    [3, "What is the diameter of a basketball hoop in inches?", "18", "16", "20", "24"],
    [3, "Which country has won the most Rugby World Cups (as of 2023)?", "South Africa", "New Zealand", "Australia", "England"],
    [3, "Which Formula 1 driver has won seven World Championships alongside Michael Schumacher?", "Lewis Hamilton", "Sebastian Vettel", "Ayrton Senna", "Max Verstappen"],
    [3, "In baseball, how many strikes make an out?", "3", "4", "2", "5"],
    [3, "What is the name of the trophy for the NFL champion?", "Vince Lombardi Trophy", "Larry O'Brien Trophy", "Commissioner's Trophy", "Stanley Cup"],
    [3, "Which martial art originated in Korea and features high kicks?", "Taekwondo", "Karate", "Judo", "Kung fu"],
    [3, "In cricket, how many balls are in a standard over?", "6", "5", "8", "10"],
    [3, "Which man has won the most Wimbledon singles titles, with eight?", "Roger Federer", "Pete Sampras", "Björn Borg", "Rafael Nadal"],
    [3, "Which city hosted the first modern Olympic Games in 1896?", "Athens", "Paris", "London", "Rome"],
    [3, "Which sport uses the terms 'spare' and 'strike'?", "Bowling", "Baseball", "Cricket", "Darts"],
    [3, "How many players are on a volleyball team on the court?", "6", "5", "7", "4"],
    [3, "Which NFL team has won the most Super Bowls (tied, as of 2024)?", "New England Patriots and Pittsburgh Steelers", "Dallas Cowboys", "San Francisco 49ers", "Green Bay Packers"],

    // Level 4 — Expert
    [4, "Which country has won the most Olympic medals overall in history?", "United States", "Soviet Union", "Germany", "Great Britain"],
    [4, "In which year did Jesse Owens win four gold medals in Berlin?", "1936", "1932", "1948", "1928"],
    [4, "Which sport did astronaut Alan Shepard play on the Moon in 1971?", "Golf", "Baseball", "Frisbee", "Soccer"],
    [4, "Which country invented table tennis as an after-dinner game?", "England", "China", "Japan", "Sweden"],
    [4, "What is the length of a cricket pitch (between the wickets)?", "22 yards", "20 yards", "25 yards", "18 yards"],
    [4, "Which boxer was the first to beat Muhammad Ali as a professional?", "Joe Frazier", "Ken Norton", "Leon Spinks", "Larry Holmes"],
    [4, "In horse racing, which three races make up the U.S. Triple Crown?", "Kentucky Derby, Preakness, Belmont", "Kentucky Derby, Epsom Derby, Belmont", "Preakness, Breeders' Cup, Belmont", "Kentucky Derby, Preakness, Travers"],
    [4, "Which gymnast scored the first perfect 10 in Olympic history, in 1976?", "Nadia Comăneci", "Olga Korbut", "Mary Lou Retton", "Simone Biles"],
    [4, "What is the regulation weight of an NBA basketball, approximately?", "22 oz", "16 oz", "28 oz", "32 oz"],
    [4, "What is a 'Hail Mary' in American football?", "A long desperate forward pass", "A trick kick", "An onside kick", "A fake punt"],
    [4, "Which country won the first Cricket World Cup in 1975?", "West Indies", "Australia", "England", "India"],
    [4, "What is the name of the trophy awarded to the winner of the NHL playoffs?", "Stanley Cup", "Grey Cup", "Calder Cup", "Hart Trophy"],
    [4, "In golf, what is a score of three under par on a single hole called?", "Albatross", "Eagle", "Condor", "Birdie"],
    [4, "Which footballer scored the 'Hand of God' goal in 1986?", "Diego Maradona", "Pelé", "Lionel Messi", "Gabriel Batistuta"],
    [4, "In which sport is the Davis Cup contested?", "Tennis", "Golf", "Sailing", "Badminton"],
    [4, "How many dimples does a standard golf ball typically have?", "Around 300 to 500", "Around 100", "Around 1,000", "Exactly 50"],
    [4, "Which city hosted the 1992 Summer Olympics featuring the U.S. 'Dream Team'?", "Barcelona", "Seoul", "Atlanta", "Los Angeles"],
    [4, "Which sprinter won the 100m at the 1988 Olympics after Ben Johnson was disqualified?", "Carl Lewis", "Linford Christie", "Calvin Smith", "Maurice Greene"],
    [4, "What is the name of the oldest tennis tournament in the world?", "Wimbledon", "US Open", "French Open", "Australian Open"],
    [4, "Which NBA player scored 100 points in a single game in 1962?", "Wilt Chamberlain", "Bill Russell", "Kareem Abdul-Jabbar", "Elgin Baylor"],
  ],
};
