'use strict';

module.exports = {
  category: "Technology",
  questions: [
    // Level 1 — Easy
    [1, "What does 'PC' stand for?", "Personal computer", "Private computer", "Public console", "Power cable"],
    [1, "Which company makes the iPhone?", "Apple", "Samsung", "Google", "Sony"],
    [1, "What do you use to point and click on a computer screen?", "Mouse", "Printer", "Speaker", "Webcam"],
    [1, "Which company runs the world's most-used search engine?", "Google", "Microsoft", "Yahoo", "Amazon"],
    [1, "What does 'Wi-Fi' let devices do?", "Connect to a network wirelessly", "Charge batteries", "Print documents", "Play music louder"],
    [1, "Which key do you press to make a new line when typing?", "Enter", "Shift", "Escape", "Tab"],
    [1, "Which company created Windows?", "Microsoft", "Apple", "IBM", "Google"],
    [1, "What is the brain of a computer called?", "CPU", "Monitor", "Keyboard", "Mouse"],
    [1, "What does 'USB' let you do?", "Connect devices to a computer", "Cool down a computer", "Speed up Wi-Fi", "Clean the screen"],
    [1, "Which company makes Galaxy smartphones?", "Samsung", "Apple", "Nokia", "Huawei"],
    [1, "What do you call a program on a smartphone?", "App", "Byte", "Chip", "Pixel"],
    [1, "What does a webcam do?", "Captures video for a computer", "Prints photos", "Plays music", "Stores files"],
    [1, "What is the screen of a computer often called?", "Monitor", "Tower", "Router", "Modem"],
    [1, "Which company's voice assistant is called Alexa?", "Amazon", "Apple", "Google", "Microsoft"],
    [1, "What is Apple's voice assistant called?", "Siri", "Alexa", "Cortana", "Bixby"],
    [1, "What do you call unwanted junk email?", "Spam", "Ham", "Spoof", "Draft"],
    [1, "Which shortcut usually copies text on Windows?", "Ctrl + C", "Ctrl + V", "Ctrl + X", "Ctrl + Z"],
    [1, "What does a printer do?", "Puts digital documents on paper", "Scans fingerprints", "Plays videos", "Stores files"],
    [1, "What is the tiny dot that makes up a digital image called?", "Pixel", "Byte", "Bit", "Chip"],
    [1, "Which device connects your home to the internet?", "Router/modem", "Monitor", "Keyboard", "Speaker"],

    // Level 2 — Medium
    [2, "What does 'CPU' stand for?", "Central processing unit", "Computer power unit", "Central program utility", "Core processing unit"],
    [2, "Who co-founded Apple with Steve Wozniak?", "Steve Jobs", "Bill Gates", "Elon Musk", "Larry Page"],
    [2, "Who co-founded Microsoft with Paul Allen?", "Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Jeff Bezos"],
    [2, "What does 'RAM' stand for?", "Random access memory", "Read and modify", "Rapid action memory", "Run all memory"],
    [2, "What does 'URL' stand for?", "Uniform Resource Locator", "Universal Resource Link", "User Request Line", "Unified Remote Location"],
    [2, "How many bits are in a byte?", "8", "4", "16", "10"],
    [2, "Which programming language is mainly used to style web pages?", "CSS", "Python", "C++", "SQL"],
    [2, "Who founded Amazon?", "Jeff Bezos", "Elon Musk", "Larry Ellison", "Jack Ma"],
    [2, "What is the name of Google's mobile operating system?", "Android", "iOS", "Windows Phone", "Symbian"],
    [2, "What does 'HTML' stand for?", "HyperText Markup Language", "High Tech Modern Language", "Hyperlink Text Machine Language", "Home Tool Markup Language"],
    [2, "Which company owns Instagram and WhatsApp?", "Meta", "Google", "Microsoft", "Snap"],
    [2, "What does 'AI' stand for?", "Artificial intelligence", "Automated input", "Advanced interface", "Analog integration"],
    [2, "Which company makes GeForce graphics cards?", "Nvidia", "AMD", "Intel", "Qualcomm"],
    [2, "What is the name for malicious software that locks your files until you pay?", "Ransomware", "Adware", "Spyware", "Freeware"],
    [2, "Which unit is bigger: a gigabyte or a megabyte?", "Gigabyte", "Megabyte", "They're equal", "It depends on the device"],
    [2, "What does 'GPS' stand for?", "Global Positioning System", "General Path Service", "Geographic Pointer Satellite", "Global Phone Signal"],
    [2, "Which company makes the Pixel phones?", "Google", "Samsung", "Apple", "OnePlus"],
    [2, "What is the term for a fake email trying to steal your password?", "Phishing", "Cookie", "Firewall", "Patching"],
    [2, "What does 'Bluetooth' mainly do?", "Short-range wireless connection between devices", "Long-range internet", "Charges devices", "Encrypts files"],
    [2, "What is the name of Tesla's CEO, as of 2024?", "Elon Musk", "Tim Cook", "Sundar Pichai", "Satya Nadella"],

    // Level 3 — Hard
    [3, "Who is considered the father of the World Wide Web?", "Tim Berners-Lee", "Vint Cerf", "Alan Turing", "Bill Gates"],
    [3, "Who is often called the father of theoretical computer science and AI?", "Alan Turing", "John von Neumann", "Charles Babbage", "Claude Shannon"],
    [3, "What does 'SSD' stand for?", "Solid-state drive", "Super speed disk", "System storage device", "Secure software drive"],
    [3, "Which company makes Snapdragon mobile chips?", "Qualcomm", "Intel", "Apple", "Nvidia"],
    [3, "Which programming language was created by Guido van Rossum?", "Python", "Java", "Ruby", "Perl"],
    [3, "What does 'HTTP' stand for?", "HyperText Transfer Protocol", "High Transfer Text Process", "Hyperlink Transmission Protocol", "Host Transfer Text Protocol"],
    [3, "Which company created the Java programming language?", "Sun Microsystems", "Microsoft", "Oracle", "IBM"],
    [3, "What is the binary representation of the number 5?", "101", "110", "111", "100"],
    [3, "What does 'GPU' stand for?", "Graphics processing unit", "General processing unit", "Graphical program utility", "Game power unit"],
    [3, "Which company makes the 'M1' and 'M2' computer chips?", "Apple", "Intel", "AMD", "Qualcomm"],
    [3, "What does 'VPN' stand for?", "Virtual private network", "Verified public node", "Visual processing network", "Virtual protocol number"],
    [3, "What is the name of the first widely used graphical web browser (1993)?", "Mosaic", "Netscape Navigator", "Internet Explorer", "Opera"],
    [3, "Who created the Linux kernel in 1991?", "Linus Torvalds", "Richard Stallman", "Dennis Ritchie", "Ken Thompson"],
    [3, "What is the term for the smallest unit of data in computing?", "Bit", "Byte", "Nibble", "Pixel"],
    [3, "What does 'IP' stand for in 'IP address'?", "Internet Protocol", "Internal Port", "Information Packet", "Internet Provider"],
    [3, "Which company created the first commercial microprocessor, the 4004?", "Intel", "AMD", "IBM", "Motorola"],
    [3, "What is open-source software?", "Software whose source code is publicly available to modify", "Software that is always free of bugs", "Software for open offices", "Software without a license"],
    [3, "What does 'LED' stand for?", "Light-emitting diode", "Low energy display", "Laser electric device", "Light energy distributor"],
    [3, "Which company acquired YouTube in 2006?", "Google", "Yahoo", "Microsoft", "Facebook"],
    [3, "What is 'cloud computing'?", "Using remote servers over the internet to store and process data", "Weather forecasting software", "Computers cooled by air", "Wireless charging"],

    // Level 4 — Expert
    [4, "Who wrote what's considered the first computer algorithm, for Babbage's Analytical Engine?", "Ada Lovelace", "Grace Hopper", "Alan Turing", "Charles Babbage"],
    [4, "Which programming language did Dennis Ritchie create at Bell Labs?", "C", "C++", "Java", "Fortran"],
    [4, "What does 'ASCII' stand for?", "American Standard Code for Information Interchange", "Advanced System Code for Internet Integration", "Automated Standard Character Input Index", "American Software Code for Integrated Interfaces"],
    [4, "What was the name of the precursor network to the internet, funded by the U.S. DoD?", "ARPANET", "NSFNET", "MILNET", "Usenet"],
    [4, "Who popularized the term 'bug' after a moth was found in a computer in 1947?", "Grace Hopper's team", "Alan Turing", "John von Neumann", "Ada Lovelace"],
    [4, "What does Moore's law predict?", "Transistor counts roughly double every two years", "Computer prices halve every year", "Internet speeds double every month", "Battery life doubles every decade"],
    [4, "What is the hexadecimal value of the decimal number 255?", "FF", "EE", "F0", "100"],
    [4, "Which company developed the first commercially successful GUI personal computer, the Macintosh (1984)?", "Apple", "Xerox", "IBM", "Commodore"],
    [4, "What does 'SQL' stand for?", "Structured Query Language", "Simple Question Language", "System Quality Log", "Sequential Query Logic"],
    [4, "What is the name of the first electronic general-purpose digital computer (1945)?", "ENIAC", "UNIVAC", "Colossus", "EDVAC"],
    [4, "What port number does HTTPS use by default?", "443", "80", "21", "8080"],
    [4, "What is the name of the test proposed to judge whether a machine can exhibit human-like intelligence?", "Turing test", "Lovelace test", "Babbage test", "Shannon test"],
    [4, "Which encryption method uses a public and a private key?", "Asymmetric encryption", "Symmetric encryption", "Hashing", "Caesar cipher"],
    [4, "What year did the World Wide Web become publicly available?", "1991", "1985", "1995", "1989"],
    [4, "What does 'DNS' do?", "Translates domain names into IP addresses", "Encrypts web traffic", "Stores website files", "Speeds up downloads"],
    [4, "What is the name of the version control system created by Linus Torvalds?", "Git", "Subversion", "Mercurial", "CVS"],
    [4, "What does 'LAN' stand for?", "Local area network", "Large access node", "Linked application network", "Long antenna network"],
    [4, "Which company created the 'Unix' operating system?", "Bell Labs (AT&T)", "IBM", "Microsoft", "Xerox PARC"],
    [4, "What is a 'zero-day' vulnerability?", "A flaw unknown to the vendor with no fix yet", "A bug fixed on day one", "A virus that deletes itself", "A password that expires daily"],
    [4, "In computing, what does 'RAID' combine?", "Multiple disks into one logical unit", "Multiple CPUs into one chip", "Multiple networks into one", "Multiple screens into one"],
  ],
};
